= D. LocalAuthorizationList Management
:!chapter-number:

== Introduction

As explained in C1.4 - Local Authorization List, the Local Authorization List is a list of identifiers that can be synchronized with the
CSMS. It allows authorization of a user when offline and when online it can be used to reduce authorization response time. This
Functional Block is for enabling the CSMS to synchronize the list by either sending a complete list of identifiers to replace the Local
Authorization List or by sending a list of changes (add, update, delete) to apply to the Local Authorization List. The operations to

support this are GetLocalListVersion and SendLocalList.
The list contains the authorization status of all (or a selection of) identifiers and the corresponding expiration date. These values

may be used to provide more fine grained information to users (e.g. by display message) during local authorization.

Edition 3 FINAL, 2024-05-06 **D. LocalAuthorizationList Management**


==  Use cases & Requirements

[[send_local_authorization_list]]
=== D01 - Send Local Authorization List

_Table 91. D01 - Send Local Authorization List_


No. Type Description
1 Name Send Local Authorization List
2 ID D01
Functional block D. Local Authorization List
3 Objective(s) To enable the CSMS to send a Local Authorization List which a Charging Station can use for the
authorization of idTokens.
4 Description The CSMS sends a Local Authorization List which a Charging Station can use for the
authorization of idTokens. The list MAY be either a full list to replace the current list in the
Charging Station or it MAY be a differential list with updates to be applied to the current list in the
Charging Station.
Actors Charging Station, CSMS

_Scenario description_ (^) **1.** The CSMS sends a SendLocalListRequest to install or update the Local Authorization List.

**2.** Upon receipt of the SendLocalListRequest the Charging Station responds with a
SendLocalListResponse with its status.
**5 Prerequisite(s)** Local Authorization List is enabled with Configuration Variable LocalAuthListEnabled.

**6 Postcondition(s)** (^) **Successful postcondition:**

- A new Local Authorization List is installed on the Charging Station.
**Failure postcondition:**
- The Local Authorization List on the Charging Station stays as it was.
- If the status is _Failed_ or _VersionMismatch_.


CSMS Charging Station


SendLocalListRequest(versionNumber, updateType,...)


SendLocalListResponse(Accepted)

_Figure 37. Sequence Diagram: Send Local Authorization List_


7 Error handling If the status is Failed or VersionMismatch and the updateType was Differential, the CSMS will
transmit the full Local Authorization List. When this list is too large for one message, it will start
by sending an initial list with updateType Full and adding identifiers using updateType Differential
until the list is completely sent (the amount of identifiers that can be sent in a single
SendLocalListRequest is limited as described in requirement D01.FR.11).
8 Remark(s) n/a

**D01 - Send Local Authorization List - Requirements**

_Table 92. D01 - Requirements_


ID Precondition Requirement definition Note
D01.FR.01 SendLocalListRequest SHALL contain the type of
update ( updateType ) and a version number
( versionNumber ) that the Charging Station MUST
associate with the Local Authorization List after it
has been updated.
D01.FR.02 SendLocalListResponse SHALL indicate whether
the Charging Station has accepted the update of
the Local Authorization List

Edition 3 FINAL, 2024-05-06 **D. LocalAuthorizationList Management**



ID Precondition Requirement definition Note
D01.FR.03 If the status in
SendLocalListResponse is Failed or
VersionMismatch and the
updateType was Differential


It is RECOMMENDED that the CSMS sends the full
Local Authorization List.


When this list is too large
for one message (see
D01.FR.11), it shall start
by sending an initial list
with updateType Full
and adding identifiers
using updateType
Differential until the
list is completely sent.
D01.FR.04 If no localAuthorizationList is given
and the updateType is Full.


The Charging Station SHALL remove all IdTokens
from the list.


Note, that the version
number of the list is still
updated to value of
versionNumber in the
request.
D01.FR.05 Requesting a Differential update without or with
empty localAuthorizationList SHALL have no effect
on the list.


Note, that the version
number of the list is still
updated to value of
versionNumber in the
request.
D01.FR.06 All IdTokens in the Local Authorization List SHALL
be unique.


No duplicate values are
allowed.
D01.FR.09 The Charging Station SHALL NOT modify the
contents of the Authorization List by any other
means than upon a the receipt of a SendLocalList
message from the CSMS.
D01.FR.10 The Local Authorization List SHOULD be
maintained by the Charging Station in non-volatile
memory, and SHOULD be persisted across reboots
and power outages.
D01.FR.11 The size of a single SendLocalListRequest is
limited by the Configuration Variables
ItemsPerMessageSendLocalList and
BytesPerMessageSendLocalList.
D01.FR.12 A Charging Station that supports Local
Authorization List SHALL implement the
Configuration Variable: LocalAuthListEntries.


This gives the CSMS a
way to known the current
amount and maximum
possible number of Local
Authorization List
elements in a Charging
Station.
D01.FR.13 The Charging Station indicates whether the Local
Authorization List is enabled. This is reported and
controlled by the LocalAuthListEnabled
Configuration Variable.
D01.FR.15 If the Charging Station receives a
SendLocalListRequest with
updateType is Full AND
localAuthorizationList is non-empty


The Charging Station SHALL replace its current
Local Authorization List with the one in the
SendLocalListRequest and set the version number
to the value specified in the message


Otherwise, there is no
way to sync the initial
Charging Station and
CSMS lists. When this list
is too large for one
message (see
D01.FR.11), it shall start
by sending an initial list
with_updateType_ Full
and adding identifiers
using updateType
Differential until the
list is completely sent.
D01.FR.16 If the Charging Station receives a
SendLocalListRequest with
updateType is Differential AND
localAuthorizationList contains
AuthorizationData elements with
idTokenInfo


The Charging Station SHALL update its Local
Authorization List with these elements and set the
version number to the value specified in the
message.


Add them if not yet
present, update with new
information when already
present in the Local
Authorization List.

Edition 3 FINAL, 2024-05-06 **D. LocalAuthorizationList Management**



ID Precondition Requirement definition Note
D01.FR.17 If the Charging Station receives a
SendLocalListRequest with
updateType is Differential AND
localAuthorizationList contains
AuthorizationData elements without
idTokenInfo


The Charging Station SHALL remove these
elements from its Local Authorization List and set
the version number to the value specified in the
message.


D01.FR.18 versionNumber in a SendLocalListRequest SHALL
be greater than 0.


In
GetLocalListVersionResp
onse the versionNumber
 0 has a special
meaning: No Local List
installed. So the value 0
should never be used.
D01.FR.19 If the Charging Station receives a
SendLocalListRequest with
updateType  Differential AND
versionNumber is less or equal to the
version number of its Local
Authorization List


The Charging Station SHALL refuse to update its
Local Authorization List and SHALL return a
SendLocalListResponse with status set to
VersionMismatch.

Edition 3 FINAL, 2024-05-06 **D. LocalAuthorizationList Management**


==== D02 - Get Local List Version.

_Table 93. D02 - Get Local List Version_


No. Type Description
1 Name Get Local List Version
2 ID D02
Functional block D. Local Authorization List
Parent use case D01 - Send Local Authorization List
3 Objective(s) To support synchronization of Local Authorization List.
4 Description The CSMS can request a Charging Station for the version number of the Local Authorization List
by sending a GetLocalListVersionRequest.
Actors Charging Station, CSMS

_Scenario description_ (^) **1.** The CSMS sends a GetLocalListVersionRequest to request this value.

**2.** Upon receipt of the GetLocalListVersionRequest Charging Station responds with a
GetLocalListVersionResponse containing the version number of its Local Authorization List.
**5 Prerequisite(s)
6 Postcondition(s)** The CSMS received the GetLocalListVersionResponse with the Local Authorization List version.


Charging Station CSMS


GetLocalListVersionRequest()


GetLocalListVersionResponse(versionNumber)

_Figure 38. Sequence Diagram: Get Local List Version_


7 Error handling n/a
8 Remark(s) A versionNumber of 0 (zero) is reserved to indicate that no local authorization list exists, either
because it is not enabled or because it has not yet received any update from CSMS and thus does
not have a version number to return.
In contrast, a local authorization list that was emptied, because CSMS sent a
SendLocalListRequest with an empty localAuthorizationList , does have a versionNumber > 0.

**D02 - Get Local List Version - Requirements**

_Table 94. D02 - Requirements_


ID Precondition Requirement definition
D02.FR.01 LocalAuthListEnabled is true When Charging Station receives GetLocalListVersionRequest
then Charging Station SHALL respond with a
GetLocalListVersionResponse containing the version number of
its Local Authorization List.

D02.FR.02 (^) LocalAuthListEnabled is _true_ AND
the CSMS has not yet sent any update to the
Charging Station for Local Authorization List
(via SendLocalListRequest)
When Charging Station receives GetLocalListVersionRequest
then Charging Station SHALL respond with a
GetLocalListVersionResponse with _versionNumber_ is 0 (zero) to
indicate that there is no Local Authorization List.
D02.FR.03 LocalAuthListEnabled is not _true_ When Charging Station receives GetLocalListVersionRequest
then Charging Station SHALL respond with a
GetLocalListVersionResponse with _versionNumber_ is 0 (zero) to
indicate that there is no Local Authorization List.
