= N. Diagnostics
:!chapter-number:

:sectnums:
== Introduction

This Functional Block describes the diagnostics functionality of OCPP. This functionality enables remote diagnostics of problems with a Charging Station. A Charging Station can be requested to upload a file with diagnostics information (optionally limited to a specified interval).

<<<

== Use cases & Requirements

=== Logging

:sectnums!:
=== N01 - Retrieve Log Information

.N01 - Retrieve Log Information
[cols="^.^1s,<.^2s,<.^7",%autowidth.stretch,options="header",frame=all,grid=all]
|===
|No. |Type            |Description

|1   |Name            |Retrieve Log
|2   |ID              |N01
|{nbsp} d|_Functional block_ |N. Diagnostics
|3   |Objective(s)    |To enable the CSMS retrieving of log information from a Charging Station.
|4   |Description     |This use case covers the functionality of getting log information from a Charging Station. The CSMS can request a Charging Station to upload a file with log information to a given location (URL). The format of this log file is not prescribed. The Charging Station uploads a log file and gives information about the status of the upload by sending status notifications to the CSMS.
|{nbsp} d|_Actors_    |Charging Station, CSMS
|{nbsp} d|_Scenario description_ 
  |**1.** The CSMS sends a <<get_log_request,GetLogRequest>> to the Charging Station. +
  **2.** The Charging Station responds with a <<get_log_response,GetLogResponse>>. +
  **3.** The Charging Station sends a <<log_status_notification_request,LogStatusNotificationRequest>> with the status Uploading +
  **4.** The CSMS responds with a <<log_status_notification_response,LogStatusNotificationResponse>> acknowledging the status update +
  request. +
  **5.** Uploading of the diagnostics files. +
  **6.** The Charging Station sends <<log_status_notification_request,LogStatusNotificationRequest>> with the status Uploaded. +
  **7.** The CSMS responds with <<log_status_notification_response,LogStatusNotificationResponse>>, acknowledging the status update request.
|5   |Prerequisite(s)
  |- Diagnostics information is available for upload. +
  - URL to upload file to is reachable and exists.
|6  |Postcondition(s)
  |**Successful postcondition:** +
  Log file successfully uploaded.

  **Failure postcondition:** +
  Log file not successfully uploaded and failed.
|===

.Sequence Diagram: Get Diagnostics
image::part2/images/figure_131.svg[Sequence Diagram: Get Diagnostics]

[cols="^.^1s,<.^2s,<.^7",%autowidth.stretch,frame=all,grid=all]
|===
|7   |Error handling |When the upload fails and the transfer protocol supports "resume" the Charging Station is RECOMMENDED to try to resume before aborting the upload.
|8   |Remark(s)      |As an example in this use case the requestId = 123, but this could be any value.

When a Charging Station is requested to upload a log file, the CSMS supplies in the request an URL where the Charging Station SHALL upload the file. The URL also contains the protocol which must be used to upload the file.

It is recommended that the log file is uploaded via FTP or FTPS. FTP(S) is better optimized for large binary data than HTTP. Also FTP(S) has the ability to resume uploads. In case an upload is interrupted, the Charging Station can resume uploading after the part it already has uploaded. The FTP URL is of format: _ftp://User:password@host:port/path_ in which the parts _User:password@_, _:password_ or _:port_ may be excluded.

The Charging Station has a required Configuration Variable that reports which file transfer protocols it supports: <<file_transfer_protocols,`FileTransferProtocols`>>

The format of the log file is not prescribed.

FTP needs to be able to use Passive FTP, to be able to transverse over as much different typologies as possible.
|===

==== N01 - Retrieve Log Information - Requirements

.N01 - Requirements
[cols="^.^1,<.^2,<.^5,<.^3",%autowidth.stretch,options="header",frame=all,grid=all]
|===
|ID         |Precondition         |Requirement definition     |Note

|N01.FR.01  |Upon receipt of a <<get_log_request,GetLogRequest>> AND +
  if the requested log information is available
    |The Charging Station SHALL respond with a <<get_log_response,GetLogResponse>> stating the name of the file and status _Accepted_. |{nbsp}
|N01.FR.02  |N01.FR.01
  |The Charging Station SHALL start uploading a single log file to the specified location |{nbsp}
|N01.FR.03  |N01.FR.02 +
  AND +
  The <<get_log_request,GetLogRequest>> contained logType _SecurityLog_
    |The Charging Station SHALL upload its security log |{nbsp}
|N01.FR.04  |N01.FR.02 +
  AND +
  The <<get_log_request,GetLogRequest>> contained logType _DiagnosticsLog_
    |The Charging Station SHALL upload its diagnostics. |{nbsp}
|N01.FR.05  |Upon receipt of a <<get_log_request,GetLogRequest>> AND +
  if the requested log information is NOT available
    |The Charging Station SHALL respond with a <<get_log_response,GetLogResponse>> WITH status _Rejected_. |{nbsp}
|N01.FR.07  |{nbsp}
  |Every <<log_status_notification_request,LogStatusNotificationRequest>> sent for a log upload SHALL contain the same requestId as the <<get_log_request,GetLogRequest>> that started this log upload. |{nbsp}
|N01.FR.08  |When uploading a log document is started
  |The Charging Station SHALL send a <<log_status_notification_request,LogStatusNotificationRequest>> with status _Uploading_. |{nbsp}
|N01.FR.09  |When a log document is uploaded successfully
  |The Charging Station SHALL send a <<log_status_notification_request,LogStatusNotificationRequest>> with status _Uploaded_. |{nbsp}
|N01.FR.10  |When uploading a log document failed
  |The Charging Station SHALL send a <<log_status_notification_request,LogStatusNotificationRequest>> with status `UploadFailure`, `BadMessage`, `PermissionDenied` OR +
  `NotSupportedOperation`.
    |It is RECOMMENDED to send the status only after all retry attempts have failed. A Charging Station MAY send a new `Uploading` status upon each retry attempt.
|N01.FR.12  |When a Charging Station is assembling or uploading the log file AND +
  the Charging Station receives a new <<get_log_request,GetLogRequest>>
    |The Charging Station SHOULD cancel the ongoing log file upload AND respond with status _AcceptedCanceled_. |{nbsp}
|N01.FR.13  |{nbsp}
  |The field requestId in <<log_status_notification_request,LogStatusNotificationRequest>> is mandatory, unless the message was triggered by a <<trigger_message_request,TriggerMessageRequest>> AND there is no log upload ongoing. |{nbsp}
|N01.FR.14  |{nbsp}
  |It is RECOMMENDED that Charging Station and CSMS support at least HTTP(s) as transport mechanism for the log file upload
    |HTTP transport is most likely to be supported, since it is also used for OCPP messaging.
|N01.FR.15  |{nbsp}
  |Charging Station SHALL at least support the CSMS trust chain for secure transports |{nbsp}
|N01.FR.16  |{nbsp}
  |It is RECOMMENDED that Charging Station supports the usual CAs provided by the operating system
    |The log file storage of CSMS may be a cloud service operated separately from the CSMS itself and not part of the CSMS trustchain.
|N01.FR.17  |When CSMS requires basic authorization for the upload
  |CSMS is RECOMMENDED to require a different basic authorization password for the upload, then the one used for OCPP connectivity.
    |This is to avoid leaking the OCPP password to 3rd parties if the log file storage is a different system. +
    Basic authorization can be added to the URL as follows: +
    _http://username:password_@csms.org/logs
|N01.FR.18  |{nbsp}
  |Is is RECOMMENDED that CSMS accepts both PUT and POST requests for uploads from Charging Station. |{nbsp}
|N01.FR.19  |When Charging Station uses a HTTP(s) POST request to upload the log file
  |Charging Station SHALL provide at least the following attributes: `Content-Type:` (e.g. application/octet-stream) and `Content-Disposition:` with a specification of the filename.
    |For example: +
    Content-Type: application/octet-stream +
    Content-Disposition: form-data; +
    name="uploadedfile"; +
    filename="logfile_20210420.zip"
|N01.FR.20  |N01.FR.12 AND +
  Charging Station cancels the log file upload
    |The Charging Station SHALL send a <<log_status_notification_request,LogStatusNotificationRequest>> with _status_ = `AcceptedCanceled`.
      |N01.FR.12 is a "SHOULD" requirement. Only send status notification when requirement is executed.
|===

:sectnums:
=== Configure Monitoring

[cols="^.^1,10",%autowidth.stretch]
|===
s|NOTE |For managing the monitoring of a Charging Station a basic understanding of Device Model concepts is essential. These concepts are explained in "OCPP 2.0.1: Part 1 - Architecture & Topology", chapter 4.
|===

:sectnums!:
=== N02 - Get Monitoring report

.N02 - Get Monitoring Report
[cols="^.^1s,<.^2s,<.^7",%autowidth.stretch,options="header",frame=all,grid=all]
|===
|No. |Type            |Description

|1   |Name            |Get Monitoring Report
|2   |ID              |N02
|{nbsp} d|_Functional block_ |N. Diagnostics
|3   |Objective(s)    |To give the CSMS the ability to retrieve a report about configured monitoring settings per component and variable.
|4   |Description     |This use case describes how the CSMS requests the Charging Station to send a report about configured monitoring settings per component and variable. Optionally, this list can be filtered on monitoringCriteria and componentVariables.
|{nbsp} d|_Actors_    |Charging Station, CSMS, CSO
|{nbsp} d|_Scenario description_
  |**1.** The CSO triggers the CSMS to request a monitoring report from a Charging Station. +
  **2.** The CSMS sends a <<get_monitoring_report_request,GetMonitoringReportRequest>> to the Charging Station. +
  **3.** The Charging Station responds with a <<get_monitoring_report_response,GetMonitoringReportResponse>>. +
  **4.** The Charging Station sends a <<notify_monitoring_report_request,NotifyMonitoringReportRequest>> to the CSMS. +
  **5.** The CSMS responds with a <<notify_monitoring_report_response,NotifyMonitoringReportResponse>>. +
  **6.** Steps #4 and #5 are repeated until all data of the monitoring report has been sent.
|5   |Prerequisite(s)   |Charging Station supports Monitoring
|6   |Postcondition(s)  |The CSMS received a report about the configured monitoring settings.
|===

.Sequence Diagram: Get Monitoring Report
image::part2/images/figure_132.svg[Sequence Diagram: Get Monitoring Report]

[cols="^.^1s,<.^2s,<.^7",%autowidth.stretch,frame=all,grid=all]
|===
|7   |Error handling |n/a
|8   |Remark(s)      |n/a
|===

==== N02 - Get Monitoring Report - Requirements

.N02 - Requirements
[cols="^.^1,<.^2,<.^5",%autowidth.stretch,options="header",frame=all,grid=all]
|===
|ID         |Precondition         |Requirement definition

|N02.FR.01  |NOT N02.FR.10 AND +
  When the Charging Station receives a <<get_monitoring_report_request,GetMonitoringReportRequest>> for supported _monitoringCriteria_ OR without _monitoringCriteria_
    |The Charging Station SHALL send a <<get_monitoring_report_response,GetMonitoringReportResponse>> with <<generic_status_enum_type,Accepted>>.
|N02.FR.02  |When the Charging Station receives a <<get_monitoring_report_request,GetMonitoringReportRequest>> for not supported _monitoringCriteria_
  |The Charging Station SHALL send a <<get_monitoring_report_response,GetMonitoringReportResponse>> with <<generic_status_enum_type,NotSupported>>.
|N02.FR.03  |N02.FR.01
  |The Charging Station SHALL send the requested information via one or more <<notify_monitoring_report_request,NotifyMonitoringReportRequest>> messages to the CSMS.
|N02.FR.04  |N02.FR.01 AND +
  The <<get_monitoring_report_request,GetMonitoringReportRequest>> contained a _requestId_
    |Every <<notify_monitoring_report_request,NotifyMonitoringReportRequest>> sent for this <<get_monitoring_report_request,GetMonitoringReportRequest>> SHALL contain the same _requestId_.
|N02.FR.05  |N02.FR.01 AND +
  _monitoringCriteria_ and _componentVariables_ are NOT both empty.
    |The set of monitors reported in one or more <<notify_monitoring_report_request,NotifyMonitoringReportRequest>> messages is limited to the set defined by _monitoringCriteria_ and _componentVariables_.
|N02.FR.06  |N02.FR.01 AND +
  _monitoringCriteria_ is NOT empty AND +
  _componentVariables_ is empty.
    |The set of monitors reported in one or more <<notify_monitoring_report_request,NotifyMonitoringReportRequest>> messages is limited to the set defined by _monitoringCriteria_.
|N02.FR.07  |{nbsp}
  |The maximum number of componentVariables in one <<get_monitoring_report_request,GetMonitoringReportRequest>> message is given by the <<items_per_message_get_report,`ItemsPerMessageGetReport`>> Configuration Variable
|N02.FR.08  |N02.FR.01 AND +
  _monitoringCriteria_ is absent AND +
  _componentVariables_ is NOT empty.
    |The set of monitors reported in one or more <<notify_monitoring_report_request,NotifyMonitoringReportRequest>> messages is limited to the set defined by _componentVariables_.
|N02.FR.09  |{nbsp}
  |The sequence number contained in the seqNo field of the <<notify_monitoring_report_request,NotifyMonitoringReportRequest>> is incremental per report. So the <<notify_monitoring_report_request,NotifyMonitoringReportRequest>> message which contains the first report part, SHALL have a seqNo with value _0_.
|N02.FR.10  |When the Charging Station receives a <<get_monitoring_report_request,GetMonitoringReportRequest>> with a combination of criteria which results in an empty result set.
  |The Charging Station SHALL respond with a <<get_monitoring_report_response,GetMonitoringReportResponse>>( _status_=`EmptyResultSet`).
|N02.FR.11  |N02.FR.01 AND +
  _monitoringCriteria_ is empty AND +
  _componentVariables_ is empty.
    |The set of all existing monitors is reported in one or more <<notify_monitoring_report_request,NotifyMonitoringReportRequest>> messages.
|N02.FR.12  |If _monitoringCriteria_ contains `ThresholdMonitoring`
  |All monitors with _type_ = `UpperThreshold` or _type_ = `LowerThreshold` are reported.
|N02.FR.13  |If _monitoringCriteria_ contains `DeltaMonitoring`
  |All monitors with _type_ = `Delta` are reported.
|N02.FR.14  |If _monitoringCriteria_ contains `PeriodicMonitoring`
  |All monitors with _type_ = `Periodic` or _type_ = `PeriodicClockAligned` are reported.
|N02.FR.16  |When Charging Station receives a <<get_monitoring_report_request,GetMonitoringReportRequest>> with _componentVariable_ elements in which _variable_ is missing
  |The Charging Station SHALL report for every _variable_ of the _component_ in _componentVariable_.
|N02.FR.17  |When Charging Station receives a <<get_monitoring_report_request,GetMonitoringReportRequest>> with _componentVariable_ elements in which _variable_ is present, but _instance_ is missing
  |The Charging Station SHALL report for every instance of the _variable_ of the _component_ in _componentVariable_.
|N02.FR.18  |N02.FR.11 AND +
  When Charging Station receives a <<get_monitoring_report_request,GetMonitoringReportRequest>> with a _component_ in a _componentVariable_ element that has a _component.evse.id_, but _component.evse.connector_ is missing
    |The Charging Station SHALL report the component(s) with this _component.name_, _component.instance_ and _component.evse.id_ for every _component.evse.connector_ , whilst taking into account N02.FR.20.
|N02.FR.19  |N02.FR.11 AND +
  When Charging Station receives a <<get_monitoring_report_request,GetMonitoringReportRequest>> with a _component_ in a _componentVariable_ element that has no _component.evse.id_
    |The Charging Station SHALL report the component(s) with this _component.name_, _component.instance_ for every _component.evse_ field (including top level component without _component.evse_), whilst taking into account N02.FR.20.
|N02.FR.20  |N02.FR.11 AND +
  When Charging Station receives a <<get_monitoring_report_request,GetMonitoringReportRequest>> with a _component_ in a _componentVariable_ element that has a value for _component.instance_
    |The Charging Station SHALL report the component(s) with this _component.name_ for every _component.instance_ field, whilst taking into account N02.FR.18, N02.FR.19.
|N02.FR.21  |N02.FR.11 AND +
  When Charging Station receives a <<get_monitoring_report_request,GetMonitoringReportRequest>> with a _component_ in a _componentVariable_ element that has no _component.instance_ field
    |The Charging Station SHALL report the component(s) with this _component.name_ for every _component.instance_ field or the component(s) without _component.instance_ field, whichever is the case, whilst taking into account N02.FR.18, N02.FR.19.
|===

=== N03 - Set Monitoring Base

_Table 218. N03 - Set Monitoring Base_


No. Type Description
1 Name Set Monitoring Base

Edition 3 FINAL, 2024-05-06 **N. Diagnostics**



No. Type Description
2 ID N03
Functional block N. Diagnostics
3 Objective(s) To give the CSMS the ability to request the Charging Station to activate a set of preconfigured
monitoring settings, as denoted by the value of MonitoringBase.
4 Description This use case describes how the CSMS requests the Charging Station to activate a set of
preconfigured monitoring settings, as denoted by the value of MonitoringBase. It is up to the
manufacturer of the Charging Station to define which monitoring settings are activated by All,
FactoryDefault and HardWiredOnly.
Actors Charging Station, CSMS, CSO

_Scenario description_ **1.** The CSO triggers the CSMS to request a Charging Station to set a monitoring base.

**2.** The CSMS sends a SetMonitoringBaseRequest to the Charging Station.
**3.** The Charging Station responds with a SetMonitoringBaseResponse.
**5 Prerequisite(s)** Charging Station supports Monitoring
**6 Postcondition(s)** The Charging Station activated the set of monitoring settings, as denoted by the value of
**MonitoringBase**.

CSO


CSMS Charging Station


request to set a monitoring base


SetMonitoringBaseRequest(monitoringBase)


SetMonitoringBaseResponse(status)

_Figure 133. Sequence Diagram: Set Monitoring Base_


7 Error handling n/a
8 Remark(s) Upon receipt of a SetMonitoringBaseRequest for HardWiredOnly or FactoryDefault the
Charging Station will discard of any previously configured custom monitors and will activate the
monitoring settings that are related to given MonitoringBase.


For a MonitoringBase  All the Charging Station will activate all pre-configured monitors and
leave previously configured custom monitors intact. This includes the custom monitors that were
created when changing an existing pre-configured monitor.


When the set of pre-configured monitors for All and FactoryDefault is the same, then the
difference between the two is, that with FactoryDefault all custom monitors are deleted
before the factory default pre-configured monitors are restored.

**N03 - Set Monitoring Base - Requirements**

_Table 219. N03 - Requirements_


ID Precondition Requirement definition
N03.FR.01 When the Charging Station accepts a
setMonitoringBaseRequest


Then the Charging Station SHALL send a
setMonitoringBaseResponse with Accepted.
N03.FR.02 When the Charging Station receives a
setMonitoringBaseRequest for a not supported
monitoringBase


Then the Charging Station SHALL send a
setMonitoringBaseResponse with NotSupported.

N03.FR.03 N03.FR.01 AND
When the Charging Station received a
setMonitoringBaseRequest with _monitoringBase_
All
Then the Charging Station SHALL activate all preconfigured
monitoring whilst leaving all installed custom monitors
(including changed preconfigured monitors) intact.
Edition 3 FINAL, 2024-05-06 **N. Diagnostics**



ID Precondition Requirement definition

N03.FR.04 N03.FR.01 AND
When the Charging Station received a
setMonitoringBaseRequest with _monitoringBase_
FactoryDefault
Then the Charging Station SHALL delete all custom monitors
(including overruled pre-configured monitors) and activate the
default monitoring settings as recommended by the
manufacturer.
N03.FR.05 N03.FR.01 AND
When the Charging Station received a
setMonitoringBaseRequest with _monitoringBase_
HardWiredOnly
Then the Charging Station SHALL clear all custom and disable all
pre-configured monitors. Only hard-wired monitors remain
active.

==== N04 - Set Variable Monitoring

_Table 220. N04 - Set Variable Monitoring_


No. Type Description
1 Name Set Variable Monitoring
2 ID N04
Functional block N. Diagnostics
3 Objective(s) To give the CSMS the ability to request the Charging Station to set monitoring triggers on
Variables.
4 Description This use case describes how the CSMS requests the Charging Station to set monitoring triggers
on Variables. Multiple triggers can be set for upper or lower thresholds, delta changes or periodic
reporting.
Actors Charging Station, CSMS, CSO

_Scenario description_ **1.** The CSO triggers the CSMS to request a Charging Station to set a variable monitoring setting.

**2.** The CSMS sends a SetVariableMonitoringRequest to the Charging Station.
**3.** The Charging Station responds with a SetVariableMonitoringResponse.

**5 Prerequisite(s)** Charging Station supports Monitoring
The specific Variable supports Monitoring
**6 Postcondition(s)** The Charging Station activated the set of monitoring triggers on the Variables.
CSO
CSMS Charging Station
request to set a monitoring setting for a variable
SetVariableMonitoringRequest(MonitoringData)
SetVariableMonitoringResponse(setMonitoringResult)
_Figure 134. Sequence Diagram: Set Variable Monitoring_
**7 Error handling** n/a
**8 Remark(s)** All variableMonitoring settings are persistent across reboot.
A variableMonitoring setting is persistent after a firmware update, if the monitored variable still
exists and it is still monitor-able. Otherwise the variableMonitoring setting is removed.
**N04 - Set Variable Monitoring - Requirements**
_Table 221. N04 - Requirements_
**ID Precondition Requirement definition Note**
N04.FR.01 When the Charging Station receives a
SetVariableMonitoringRequest with an
X number of SetMonitoringData
elements
The Charging Station SHALL respond with an
SetVariableMonitoringResponse with an equal (X)
number of SetMonitoringResult elements, one for
every SetMonitoringData element in the
SetVariableMonitoringRequest.
Edition 3 FINAL, 2024-05-06 **N. Diagnostics**



ID Precondition Requirement definition Note
N04.FR.02 N04.FR.01 Every SetMonitoringResult element in the
SetVariableMonitoringResponse SHALL contain the
same component and variable combination as one
of the SetVariableMonitoringRequest elements in
the SetVariableMonitoringRequest.
N04.FR.03 When the Charging Station receives a
SetVariableMonitoringRequest with an
unknown Component in
SetMonitoringData


The Charging Station SHALL set the attributeStatus
field in the corresponding SetMonitoringResult to:
UnknownComponent.


N04.FR.04 When the Charging Station receives a
SetVariableMonitoringRequest with a
Variable that is unknown for the given
Component in SetMonitoringData


The Charging Station SHALL set the attributeStatus
field in the corresponding SetMonitoringResult to:
UnknownVariable.


N04.FR.05 When the Charging Station receives a
SetVariableMonitoringRequest with an
MonitorType which is not supported
by the specific Variable


The Charging Station SHALL set the attributeStatus
field in the corresponding SetMonitoringResult to:
UnsupportedMonitorType.


N04.FR.06 When the Charging Station receives a
SetVariableMonitoringRequest with
monitor type UpperThreshold or
LowerThreshold AND
the monitorValue is lower or higher
than the range of the given Variable


The Charging Station SHALL set the attributeStatus
field in the corresponding SetMonitoringResult to:
Rejected.


More information can be
provided in the optional
statusInfo element.


N04.FR.07 When the Charging Station receives a
SetVariableMonitoringRequest for a
monitor that conflicts with safety
requirements.


The Charging Station MAY set the attributeStatus
field in the corresponding SetMonitoringResult to:
Rejected.


e.g. when the requested
monitoring overrides
factory set security
monitoring.
N04.FR.08 When the Charging Station was able
to set the given monitorValue in the
SetMonitoringData


The Charging Station SHALL set the attributeStatus
field in the corresponding SetMonitoringResult to:
Accepted.


Please refer to use case
N07 - Alert Event on how
to handle the different
monitor types.
N04.FR.09 The maximum size and number of items of
monitoringData in one
SetVariableMonitoringRequest message is
determined by the
ItemsPerMessageSetVariableMonitoring
and
BytesPerMessageSetVariableMonitoring
Configuration Variables.
N04.FR.10 When the Charging Station receives a
SetVariableMonitoringRequest for a
component / variable combination for
which a monitor with the same type
and severity already exists with a
different id.


The Charging Station SHALL set the attributeStatus
field in the corresponding SetMonitoringResult to:
Duplicate.


There cannot be two
monitors of the same
type with the same
severity on the same
variable. E.g. when a
component/variable has
a monitor with an
UpperThreshold at value
"67" and severity "4-
Error", then there cannot
be another
UpperThreshold at value
"78" with same severity
"4-Error" defined.
N04.FR.11 When the Charging Station receives a
SetVariableMonitoringRequest without
an Id AND
N04.FR.08


The Charging Station will generate an Id and return
it in the SetVariableMonitoringResponse.

Edition 3 FINAL, 2024-05-06 **N. Diagnostics**



ID Precondition Requirement definition Note
N04.FR.12 When the Charging Station receives a
SetVariableMonitoringRequest with an
Id AND
A monitor exists matching the given Id
AND
The given Component/Variable
combination corresponds with the
existing VariableMonitor.


The Charging Station SHALL replace the monitor.


N04.FR.13 When the Charging Station receives a
SetVariableMonitoringRequest with an
Id AND
No monitor exists matching the given
Id.


The Charging Station SHALL set the attributeStatus
field in the corresponding SetMonitoringResult to:
Rejected.


N04.FR.14 When the Charging Station receives a
SetVariableMonitoringRequest with
type Delta and value contains a
negative value.


The Charging Station SHALL set the attributeStatus
field in the corresponding SetMonitoringResult to:
Rejected.


More information can be
provided in the optional
statusInfo element.

N04.FR.15 N04.FR.12 AND
The replaced VariableMonitor
belonged to the
'PreconfiguredMonitors'.
The new VariableMonitor shall be classified as a
'CustomMonitor', until reset by a
SetMonitoringBaseRequest.
N04.FR.16 When the Charging Station receives a
SetVariableMonitoringRequest with an
Id AND
a monitor exists matching the given Id
AND
the given Component/Variable
combination does NOT correspond
with the existing VariableMonitor.
The Charging Station SHALL respond with _Rejected_
AND NOT replace the VariableMonitor.
It is not allowed to
change Variable or
Component of a monitor.
N04.FR.17 When the CSMS sends a
SetVariableMonitoringRequest with
type Delta for a Variable that is NOT of
a numeric type
It is RECOMMENDED to use a _monitorValue_ of 1. _monitorValue_ is irrelevant
for non-numeric types
(e.g. any type except
decimal or integer), since
the monitor is triggered
by every change of the
Variable.
N04.FR.18 N04.FR.12 AND
The _id_ in the
SetVariableMonitoringRequest refers
to a HardWiredMonitor
The Charging Station SHALL respond with _Rejected_
AND NOT replace the VariableMonitor.
It is not possible to
change a hardwired
monitor.
N04.FR.19 The Charging Station has rebooted The CSMS IS RECOMMENDED to send a
GetMonitoringReportRequest message to get a new
list of monitors.
Custom monitors are
persistent after reboot or
firmware update, but IDs
may have changed.

==== N05 - Set Monitoring Level.

_Table 222. N05 - Set Monitoring Level_


No. Type Description
1 Name Set Monitoring Level
2 ID N05
Functional block N. Diagnostics
3 Objective(s) To give the CSMS the ability to request the Charging Station to restrict the reporting of monitoring
events by NotifyEventRequest to only those monitors with a severity number lower than or equal
to a certain severity.
4 Description It may be desirable to restrict the reporting of monitoring events, to only those monitors with a
severity number lower than or equal to a certain severity. For example when the data-traffic
between Charging Station and CSMS needs to limited for some reason. The CSMS can control
which events it will to be notified of by the Charging Station with the SetMonitoringLevelRequest
message.

Edition 3 FINAL, 2024-05-06 **N. Diagnostics**



No. Type Description
Actors Charging Station, CSMS, CSO
Scenario description 1. The CSO triggers the CSMS to request a Charging Station to restrict the reporting of monitoring
events, by setting a severity level limit.

**2.** The CSMS sends a SetMonitoringLevelRequest to the Charging Station.
**3.** The Charging Station responds with a SetMonitoringLevelResponse.
**5 Prerequisite(s)** Charging Station supports Monitoring
**6 Postcondition(s)** The Charging Station restricted the reporting of monitoring events by NotifyEventRequest to only
those wanted by the user.

CSO


CSMS Charging Station


request to set a monitoring severity level


SetMonitoringLevelRequest(severity)


SetMonitoringLevelResponse(status)

_Figure 135. Sequence Diagram: Set Monitoring Level_


7 Error handling n/a
8 Remark(s) n/a

**N05 - Set Monitoring Level - Requirements**

_Table 223. N05 - Requirements_


ID Precondition Requirement definition
N05.FR.01 When the Charging Station accepts a
setMonitoringLevelRequest


The Charging Station SHALL send a
setMonitoringLevelResponse with Accepted.
N05.FR.02 When the Charging Station receives a
setMonitoringLevelRequest for a severity that is
out of range


The Charging Station SHALL send a
setMonitoringLevelResponse with Rejected.


N05.FR.03 N05.FR.01 The Charging Station SHALL restrict the reporting of monitoring
events by NotifyEventRequest to only those monitors with a
severity number lower than or equal to the given severity.

==== N06 - Clear / Remove Monitoring

_Table 224. N06 - Clear / Remove Monitoring_


No. Type Description
1 Name Clear / Remove Monitoring
2 ID N06
Functional block N. Diagnostics
3 Objective(s) To give the CSMS the ability to clear / remove monitoring settings.
4 Description A monitoring setting can be cleared (removed) by sending a ClearVariableMonitoringRequest with
the id of the monitoring setting.
Actors Charging Station, CSMS, CSO
Scenario description 1. The CSO triggers the CSMS to request clearing/removing one or more variables in a Charging
Station.

**2.** The CSMS sends a ClearVariableMonitoringRequest to the Charging Station.
**3.** The Charging Station responds with a ClearVariableMonitoringResponse.
**5 Prerequisite(s)** Charging Station supports Monitoring
**6 Postcondition(s)** The Charging Station cleared / removed the requested monitoring settings.

Edition 3 FINAL, 2024-05-06 **N. Diagnostics**



CSO


CSMS Charging Station


request to clear/remove a variable monitoring


ClearVariableMonitoringRequest(id)


ClearVariableMonitoringResponse(status)

_Figure 136. Sequence Diagram: Clear / Remove Monitoring_


7 Error handling n/a
8 Remark(s) n/a

**N06 - Clear / Remove Monitoring - Requirements**

_Table 225. N06 - Requirements_


ID Precondition Requirement definition
N06.FR.01 When the Charging Station accepts a
ClearVariableMonitoringRequest


The Charging Station SHALL send a
ClearVariableMonitoringResponse with Accepted.
N06.FR.02 When the Charging Station receives a
ClearVariableMonitoringRequest with a non
existing id


The Charging Station SHALL send a
ClearVariableMonitoringResponse with NotFound.


N06.FR.03 When the Charging Station receives a
ClearVariableMonitoringRequest for an id
referring to a monitor that cannot be cleared (for
example because it is hardcoded).


The Charging Station SHALL send a
ClearVariableMonitoringResponse with Rejected.


N06.FR.04 The CSMS SHALL NOT put more id elements in a
ClearVariableMonitoringRequest than reported by the Charging
Station via: ItemsPerMessageClearVariableMonitoring
and BytesPerMessageClearVariableMonitoring.
N06.FR.05 For every id in a ClearVariableMonitoringRequest the Charging
Station SHALL add a clearMonitoringResult element to the
ClearVariableMonitoringResponse sent to the CSMS.
N06.FR.06 Charging Station receives a
ClearVariableMonitoringRequest with more id
elements than allowed by
ItemsPerMessageClearVariableMonitor
ing


The Charging Station MAY respond with a
CALLERROR(OccurenceConstraintViolation)


N06.FR.07 Charging Station receives a
ClearVariableMonitoringRequest with a length of
more bytes than allowed by
BytesPerMessageClearVariableMonitor
ing


The Charging Station MAY respond with a
CALLERROR(FormatViolation)

==== 2.3. Monitoring Events

==== N07 - Alert Event

_Table 226. N07 - Alert Event_


No. Type Description
1 Name Alert Event
2 ID N07
Functional block N. Diagnostics
3 Objective(s) To give the Charging Station the ability to notify the CSMS about monitoring events.

Edition 3 FINAL, 2024-05-06 **N. Diagnostics**



No. Type Description
4 Description NotifyEventRequest reports every Component/Variable for which a VariableMonitoring setting
was triggered. Only the VariableMonitoring settings that are responsible for triggering an event
are included.
Actors Charging Station, CSMS
Scenario description 1. If a threshold or a delta value has exceeded, the Charging Station sends a NotifyEventRequest
to the CSMS.

**2.** The CSMS responds with a NotifyEventResponse.

**5 Prerequisite(s)** The Charging Station has active monitoring settings.
The monitoring setting(s) might have been configured explicitly via a SetVariableMonitoring
message or it might be "hard-wired" in the Charging Station’s firmware.
**6 Postcondition(s)** The Charging Station notified the CSMS about the monitoring events.
Charging Station CSMS
alt [If a threshold or a delta value of a monitoring setting has been reached]
loop [For each report part]
NotifyEventRequest(generatedAt, tbc, seqNo, eventData)
NotifyEventResponse()
_Figure 137. Sequence Diagram: Alert Event_
**7 Error handling** n/a
**8 Remark(s)** Requirement N07.FR.04 states that events with a severity equal or less than
OfflineMonitoringEventQueuingSeverity shall be queued while the charging station is offline, and
delivered once online. This implies that events with a severity greater than
OfflineMonitoringEventQueuingSeverity will not be sent to CSMS. The result is, that the logical
chain of events may be broken when the charging station is back online.
For example, a monitoring event for a variable exceeding a threshold occurred while offline and
was not sent. Once back online, at some point in time the monitoring event is reported with the
variable _cleared_ set to true, but CSMS did not even know that the threshold had been exceeded.
CSMS will have to be able to deal with that.
This problem can be prevented, while still adhering to the specification, by not simply discarding
these monitoring events, but by delaying the evaluation of those monitors that exceed
OfflineMonitoringEventQueuingSeverity, until the charging station comes back online. The result
is, that when the charging station is back online, CSMS will get the monitoring events that apply to
the current situation, and it is fully up-to-date regarding the monitors. Only those monitoring
events that were triggered & cleared during the offline period will remain invisible to CSMS.
**N07 - Alert Event - Requirements**
_Table 227. N07 - Requirements_
**ID Precondition Requirement definition Note**
N07.FR.02 When a monitored value returns to
within the set _UpperThreshold_ or
_LowerThreshold_
The Charging Station SHALL send a
NotifyEventRequest with an eventData with the
attribute _cleared_ is true.
N07.FR.03 When the CSMS receives an
notifyEventRequest
The CSMS SHALL respond with an empty
NotifyEventResponse.
Edition 3 FINAL, 2024-05-06 **N. Diagnostics**



ID Precondition Requirement definition Note

N07.FR.04 When a monitor is triggered AND
The severity number of the monitor is
equal to or lower than the severity
number set in the Configuration
Variable
OfflineMonitoringEventQueuin
gSeverity
AND
The Charging Station is _offline_
The Charging Station SHALL queue this
NotifyEventRequest and deliver it when it is back
online.
N07.FR.05 When a monitor is triggered AND
another event caused this event
The Charging Station MAY include the _eventId_ of
the other event in the _cause_ field of the eventData
element in the NotifyEventRequest message.
N07.FR.06 When a monitor is triggered An eventData element in a NotifyEventRequest
SHALL contain the Component, Variable and
_variableMonitoringId_ that caused the event.
N07.FR.07 When a monitor is triggered The Charging Station SHALL set the _seqNo_ of the
first NotifyEventRequest sent for this event to 0.
N07.FR.10 When a monitor is triggered AND
A variableMonitoring setting has been
set on a write-only variable.
The actualField of the NotifyEventRequest SHALL
be empty.
N07.FR.11 When modifying a set _UpperThreshold_
or _LowerThreshold_ VariableMonitor.
The Charging Station SHALL check if the new
threshold clears the old threshold OR if the new
threshold is exceeded by the monitored value.
N07.FR.12 When removing a set _UpperThreshold_
or _LowerThreshold_ VariableMonitor
AND
the threshold was exceeded.
The Charging Station SHALL NOT send a
NotifyEventRequest with an eventData with the
attribute _cleared_ is true.
N07.FR.13 A VariableMonitoring needs to be stored
persistently across reboots.
N07.FR.14 When a variableMonitoring setting of
type _UpperThreshold_ or
_LowerThreshold_ has been triggered
AND after a reboot occurred the
monitored value returned within the
configured threshold.
The Charging Station SHALL send a
NotifyEventRequest with an eventData with the
attribute _cleared_ is true.
N07.FR.15 When a monitor is triggered AND
The _severity_ of the monitor is greater
than the monitoring severity level set
in a SetMonitoringLevelRequest by the
CSMS (see use case N05 - Set
Monitoring Level)
The Charging Station SHALL NOT send a
NotifyEventRequest for the triggered monitor.
N07.FR.16 When there is a monitor with type
UpperThreshold on a
Component/Variable combination
AND
the Actual value (attributeType Actual)
of the Variable exceeds _monitorValue_
The Charging Station SHALL send a
NotifyEventRequest with _trigger_ Alerting for the
triggered monitor.
Notification is sent when
exceeding the threshold,
not on the threshold.
N07.FR.17 When there is a monitor with type
LowerThreshold on a
Component/Variable combination
AND
the Actual value (attributeType Actual)
of the Variable drops below
_monitorValue_
The Charging Station SHALL send a
NotifyEventRequest with _trigger_ Alerting for the
triggered monitor.
Notification is sent when
dropping below the
threshold, not on the
threshold.
Edition 3 FINAL, 2024-05-06 **N. Diagnostics**



ID Precondition Requirement definition Note
N07.FR.18 When there is a monitor with type
Delta on a Component/Variable
combination AND
the Variable is of a numeric type AND
the Actual value (attributeType Actual)
of the Variable has changed more
than plus or minus monitorValue since
the time that this monitor was set or
since the last time this event notice
was sent, whichever was last


The Charging Station SHALL send a
NotifyEventRequest with trigger Delta for the
triggered monitor.


N07.FR.19 When there is a monitor with type
Delta on a Component/Variable
combination AND
the Variable is NOT of a numeric type
AND
the Actual value (attributeType Actual)
of the Variable has changed since the
time that this monitor was set or since
the last time this event notice was
sent, whichever was last (Note: For
variables that are not numeric, like
boolean, string or enumerations, a
monitor of type Delta will trigger an
event notice whenever the variable
changes, regardless of the value of
monitorValue )


The Charging Station SHALL send a
NotifyEventRequest with trigger Delta for the
triggered monitor.

==== N08 - Periodic Event

_Table 228. N08 - Periodic Event_


No. Type Description
1 Name Periodic Event
2 ID N08
Functional block N. Diagnostics
3 Objective(s) To give the Charging Station the ability to notify the CSMS periodically about monitoring events.
4 Description NotifyEventRequest reports every Component/Variable for which a VariableMonitoring setting
was triggered. Only the VariableMonitoring settings that are responsible for triggering an event
are included.
Actors Charging Station, CSMS
Scenario description 1. If a periodic value has exceeded, the Charging Station sends a NotifyEventRequest with trigger
periodic to the CSMS.

**2.** The CSMS responds with a NotifyEventResponse.

**5 Prerequisite(s)** The Charging Station has active monitoring settings.
The monitoring setting(s) might have been configured explicitly via a SetVariableMonitoring
message or it might be "hard-wired" in the Charging Station’s firmware.
**6 Postcondition(s)** The Charging Station notified the CSMS about the monitoring events.
Charging Station CSMS
loop [Each time the periodic value of a monitoring setting has been reached]
loop [For each report part]
NotifyEventRequest(generatedAt, tbc, seqNo, eventData)
NotifyEventResponse()
_Figure 138. Sequence Diagram: Periodic Event_
**7 Error handling** n/a
Edition 3 FINAL, 2024-05-06 **N. Diagnostics**



8 Remark(s) n/a

**N08 - Periodic Event - Requirements**

_Table 229. N08 - Requirements_


ID Precondition Requirement definition
N08.FR.02 When the CSMS receives an NotifyEventRequest The CSMS SHALL respond with an empty NotifyEventResponse.

N08.FR.03 N08.FR.06 OR N08.FR.07
AND
The severity number of the monitor is equal to
or lower than the severity number set in the
Configuration Variable
OfflineMonitoringEventQueueingSever
ity
AND
The Charging Station is _offline_
The Charging Station SHALL queue this NotifyEventRequest and
deliver it when it is back online.
N08.FR.04 N08.FR.06 OR N08.FR.07 AND
This NotifyEventRequest is the first or only
report part.
The Charging Station SHALL set _seqNo_ to 0.
N08.FR.05 N08.FR.06 OR N08.FR.07 AND
When the variableMonitoring setting which
triggered the event is either of type Periodic or
PeriodicClockAligned
The Charging Station SHALL set _trigger_ to Periodic.
N08.FR.06 When there is a monitor with type Periodic on a
Component/Variable combination AND
the number of seconds specified in
_monitorValue_ have passed (starting from the
time that this monitor was set or triggered)
The Charging Station SHALL send a NotifyEventRequest with
_trigger_ Periodic for the triggered monitor.
N08.FR.07 When there is a monitor with type
PeriodicClockAligned on a Component/Variable
combination AND
the number of seconds specified by
_monitorValue_ , starting from the nearest clock-
aligned interval after this monitor was set, have
passed (For example, a _monitorValue_ of 900 will
trigger event notices at 0, 15, 30 and 45 minutes
after the hour, every hour)
The Charging Station SHALL send a NotifyEventRequest with
_trigger_ Periodic for the triggered monitor.
Edition 3 FINAL, 2024-05-06 **N. Diagnostics**


==== 2.4. Customer Information.

==== N09 - Get Customer Information

_Table 230. N09 - Get Customer Information_


No. Type Description
1 Name Get Customer Information
2 ID N09
Functional block N. Diagnostics
3 Objective(s) To enable the CSMS to retrieve raw customer information from a Charging Station.
4 Description The CSMS sends a message to the Charging Station to retrieve raw customer information, for
example to be compliant with local privacy laws. The Charging Station notifies the CSMS by
sending one or more reports.
Actors Charging Station, CSMS
Scenario description 1. The CSMS sends a CustomerInformationRequest with the report flag set to true to the Charging
Station with a reference to a customer (idToken, customerCertificate or customerIdentifier).

**2.** The Charging Station responds with CustomerInformationResponse, indicating whether it will
send it or not.
**3.** The Charging Station sends one or more NotifyCustomerInformationRequest messages to the
CSMS.
**4.** The CSMS responds with one or more NotifyCustomerInformationResponse messages to the
Charging Station.
**5 Prerequisite(s)** n/a
**6 Postcondition(s)** The CSMS has _Successfully_ received a CustomerInformationResponse message with status
_Accepted_ AND has _Successfully_ received the requested data.


CSMS Charging Station


CustomerInformationRequest(report  true, clear  false)


CustomerInformationResponse()


loop [for each report part]
NotifyCustomerInformationRequest()


NotifyCustomerInformationResponse()

_Figure 139. Sequence Diagram: Get Customer Information_


7 Error handling n/a
8 Remark(s) n/a

Edition 3 FINAL, 2024-05-06 **N. Diagnostics**


**N09 - Get Customer Information - Requirements**

_Table 231. N09 - Requirements_


ID Precondition Requirement definition Note
N09.FR.01 When the CSMS wants to retrieve
CustomerInformation from the
Charging Station.


The report flag in the CustomerInformationRequest
SHALL be set to true.


N09.FR.02 When the Charging Station receives a
CustomerInformationRequest AND
it is in a state where it can process
this request.


the Charging Station SHALL respond with a
CustomerInformationResponse message with
status Accepted.


N09.FR.03 When the Charging Station is in a
state where it cannot process this
request.


On receipt of the CustomerInformationRequest the
Charging Station SHALL respond with a
CustomerInformationResponse with status
Rejected.
N09.FR.04 The CSMS SHALL include a reference to a
customer by including either an idToken,
customerCertificate or customerIdentifier in the
CustomerInformationRequest.

N09.FR.05 N09.FR.02 AND
the Charging Station has information
stored about the customer referred to
by the customer identifier
The Charging Station SHALL send the requested
information via one or more
NotifyCustomerInformationRequest messages to
the CSMS.
N09.FR.06 N09.FR.02 AND
the Charging Station has no
information stored about the
customer referred to by the customer
identifier.
The Charging Station SHALL send one
NotifyCustomerInformationRequest message to
the CSMS indicating that no data was found.
N09.FR.07 When receiving a
CustomerInformationRequest with
both the report flag as well as the
clear flag are set to _false_
It is RECOMMENDED to respond with status a
CustomerInformationResponse message with
status _Rejected_.
N09.FR.08 When requesting user information
according to the _customerCertificate_
The CSMS SHALL use the _hashAlgorithm_ , which
was used to install the certificate.
When a new firmware is
installed it is
RECOMMENDED that the
CSMS requests the
certificate first using
GetInstalledCertificateIds
Request to be sure of the
used _hashAlgorithm_.
N09.FR.09 When CustomerInformationRequest
contains none of _idToken_ ,
_customerCertificate_ or
_customerIdentifier_ OR
CustomerInformationRequest
contains more than one of _idToken_ ,
_customerCertificate_ or
_customerIdentifier_
Charging Station SHALL respond with _status_ =
Invalid
Only one value for either
_idToken_ ,
_customerCertificate_ or
_customerIdentifier_ may
be provided.
Charging Station
counterpart requirement
of N09.FR.04.

==== N10 - Clear Customer Information

_Table 232. N10 - Clear Customer Information_


No. Type Description
1 Name Clear Customer Information
2 ID N10
Functional block N. Diagnostics
3 Objective(s) To enable the CSMS to clear (and retrieve) raw customer information from a Charging Station.
4 Description The CSMS sends a message to the Charging Station to clear (and retrieve) raw customer
information, for example to be compliant with local privacy laws. The Charging Station notifies
the CSMS by sending one or more reports.

Edition 3 FINAL, 2024-05-06 **N. Diagnostics**



No. Type Description
Actors Charging Station, CSMS
Scenario description 1. The CSMS sends CustomerInformationRequest with the clear flag set to true to the Charging
Station with a reference to a customer (idToken, customerCertificate or customerIdentifier).

**2.** The Charging Station responds with CustomerInformationResponse, indicating whether it will
send it or not.
**3.** If the report flag is set to _true_ , the Charging Station sends one or more
NotifyCustomerInformationRequest messages to the CSMS.
**4.** The CSMS responds with one or more NotifyCustomerInformationResponse messages to the
Charging Station.
**5 Prerequisite(s)** n/a
**6 Postcondition(s)** The CSMS has _Successfully_ received a CustomerInformationResponse message with status
_Accepted_ , the Charging Station has removed the customer information as requested and (if report
flag was set to _true_ ) the CSMS has _Successfully_ received the removed data.


CSMS Charging Station


CustomerInformationRequest(report, clear  true)
CustomerInformationResponse()


opt [if report  true]
loop [for each report part]
NotifyCustomerInformationRequest()
NotifyCustomerInformationResponse()


clear customer information

_Figure 140. Sequence Diagram: Clear Customer Information_


7 Error handling n/a
8 Remark(s) n/a

**N10 - Clear Customer Information - Requirements**

_Table 233. N10 - Requirements_


ID Precondition Requirement definition Note
N10.FR.01 When the Charging Station receives a
CustomerInformationRequest AND
it is in a state where it can process
this request.


the Charging Station SHALL respond with a
CustomerInformationResponse message with
status Accepted.


N10.FR.02 When the Customer referred to by the
customer identifier is present in the
Local Authorization List of a Charging
Station


The CSMS SHALL update the Local Authorization
List using the SendLocalListRequest (see D01 -
Send Local Authorization List).


To prevent problems with
Local Authorization List
versions.

N10.FR.03 N10.FR.01 AND
receiving a
CustomerInformationRequest with the
clear flag set to _true_ and the report
flag set to _true_ AND
the Charging Station has information
stored about the customer referred to
by the customer identifier.
The Charging Station SHALL remove all customer
related data for the Customer referred to by the
customer identifier from the Charging Station,
except from the LocalList AND the Charging Station
SHALL send the cleared information via one or
more NotifyCustomerInformationRequest
messages to the CSMS.
To prevent problems with
LocalList versions only
the CSMS can change
the contents of the
LocalList.
Edition 3 FINAL, 2024-05-06 **N. Diagnostics**



ID Precondition Requirement definition Note

N10.FR.04 N10.FR.01 AND
receiving a
CustomerInformationRequest with the
clear flag set to _true_ and the report
flag set to _true_ AND
the Charging Station has no
information stored about the
customer referred to by the customer
identifier.
The Charging Station SHALL send one
NotifyCustomerInformationRequest message to
the CSMS indicating that no data was found.
N10.FR.05 When the Charging Station receives a
CustomerInformationRequest and is
in a state where it cannot process this
request.
The Charging Station SHALL respond with a
CustomerInformationResponse with status
_Rejected_
N10.FR.06 N10.FR.01 AND
receiving a
CustomerInformationRequest with the
clear flag set to _true_ , the report flag
set to _false_
The Charging Station SHALL remove all customer
related data for the Customer referred to by the
customer identifier from the Charging Station,
except from the LocalList AND the Charging Station
SHALL send one
NotifyCustomerInformationRequest message to
the CSMS indicating that the data was cleared.
To prevent problems with
LocalList versions only
the CSMS can change
the contents of the
LocalList.
N10.FR.07 When receiving a
CustomerInformationRequest with
both the report flag as well as the
clear flag are set to _false_
It is RECOMMENDED to respond with a
CustomerInformationResponse message with
status _Rejected_.
N10.FR.08 The CSMS SHALL include a reference to a
customer by including either an idToken,
customerCertificate or customerIdentifier in the
CustomerInformationRequest.
N10.FR.09 When clearing user information
according to the _customerCertificate_
The CSMS SHALL use the _hashAlgorithm_ , which
was used to install the certificate.
When a new firmware is
installed it is
RECOMMENDED that the
CSMS requests the
certificate first using
GetInstalledCertificateIds
Request to be sure of the
used _hashAlgorithm_.

