@startuml figure_16
!include style.puml

participant "Charge Point" as ChargePoint
participant "Central System" as CentralSystem

ChargePoint -> CentralSystem : FirmwareStatusNotification.req(status)

activate ChargePoint
activate CentralSystem

CentralSystem -> ChargePoint : FirmwareStatusNotification.conf()

deactivate CentralSystem
deactivate ChargePoint

@enduml