@startuml figure_3
!include style.puml

participant "Charge Point" as ChargePoint
participant "Central System" as CentralSystem

ChargePoint -> CentralSystem: SendLocalList.req( **listVersion: 234**  ,  **updateType: Full**  , [localAuthorizationList])
activate ChargePoint
activate CentralSystem
CentralSystem -> ChargePoint : SendLocalList.conf( **status: Accepted** )
deactivate ChargePoint
deactivate CentralSystem

@enduml