@startuml figure_6
!include component_diagram_style.puml

left to right direction

node "Central System" as CentralSystem

folder "Charge Point: CP10" as CP10Folder {
  node "Charge Point\nCP10" as CP10

  node "Connector\n1" as CP10_C1
  node "Connector\n2" as CP10_C2
}

folder "Charge Point: CP11" as CP11Folder {
  node "Charge Point\nCP11" as CP11

  node "Connector\n1" as CP11_C1
  node "Connector\n2" as CP11_C2
}

actor "EV1" as EV1
actor "EV2" as EV2

note top of CentralSystem
  CS sets known physical
  grid connections limits
end note

CentralSystem -down-> CP10 : OCPP charging profile
CentralSystem -down-> CP11 : OCPP charging profile

CP10 -down- CP10_C1
CP10 -down- CP10_C2

CP11 -down- CP11_C1
CP11 -down- CP11_C2

CP10_C1 -down[dotted]-> EV1 : Control Pilot signal
CP10_C2 -down[dotted]-> EV2 : Control Pilot signal

@enduml