@startuml figure_22
!include style.puml

participant "Charge Point" as ChargePoint
participant "Central System" as CentralSystem

CentralSystem -> ChargePoint : CancelReservation.req(reservationId)

activate ChargePoint
activate CentralSystem

ChargePoint -> CentralSystem : CancelReservation.conf(status)

deactivate CentralSystem
deactivate ChargePoint

@enduml