@startuml figure_24
!include style.puml

participant "Charge Point" as ChargePoint
participant "Central System" as CentralSystem

CentralSystem -> ChargePoint : ChangeConfiguration.req(key, value)

activate ChargePoint
activate CentralSystem

ChargePoint -> CentralSystem : ChangeConfiguration.conf(status)

deactivate CentralSystem
deactivate ChargePoint

@enduml