' Copyright (c) 2024 phoi5675
' 
' This software is released under the MIT License.
' https://opensource.org/licenses/MIT

!define BASE_COLOR #7d5393
!define FONT_NAME NanumGothic

hide footbox

skinparam participant {
  BackgroundColor BASE_COLOR
  BorderColor #000000
  FontColor #ffffff
  FontName FONT_NAME
}

skinparam note {
  BackgroundColor BASE_COLOR
  BorderColor #000000
  FontColor #ffffff
  FontName FONT_NAME
}

skinparam ArrowFontName FONT_NAME