
!define BASE_COLOR #7d5393
!define FONT_NAME NanumGothic

hide footbox

<style>
' Sequence diagram
participant {
  BackgroundColor BASE_COLOR
  BorderColor #000000
  FontColor #ffffff
  FontName FONT_NAME
}

actor {
  LineThickness 1.5
  LineColor BASE_COLOR
  FontName FONT_NAME
}
</style>

skinparam note {
  BackgroundColor BASE_COLOR
  BorderColor #000000
  FontColor #ffffff
  FontName FONT_NAME
}

skinparam SequenceGroupFontName FONT_NAME
skinparam SequenceGroupHeaderFontName FONT_NAME

skinparam ArrowFontName FONT_NAME

' Class diagram
hide empty members
skinparam class {
  BackgroundColor white
  AttributeFontColor black
  AttributeFontName FONT_NAME

  FontName FONT_NAME

  HeaderBackgroundColor BASE_COLOR
  FontColor white

  BorderColor BASE_COLOR
  BorderThickness 1.5px
}

skinparam circle {
  BorderColor BASE_COLOR
  BackgroundColor white
}