
!define BASE_COLOR #7d5393
!define FONT_NAME NanumGothic

hide footbox

skinparam participant {
  BackgroundColor BASE_COLOR
  BorderColor #000000
  FontColor #ffffff
  FontName FONT_NAME
}

skinparam note {
  BackgroundColor BASE_COLOR
  BorderColor #000000
  FontColor #ffffff
  FontName FONT_NAME
}

skinparam SequenceGroupFontName FONT_NAME
skinparam SequenceGroupHeaderFontName FONT_NAME

skinparam ArrowFontName FONT_NAME