@startuml figure_24
!include style.puml

actor "EV Driver" as EVDriver
participant "Charging Station" as ChargingStation
participant "CSMS" as CSMS

EVDriver -> ChargingStation: enter pin-code(1234)

ChargingStation -> CSMS: \
  AuthorizeRequest(idToken(id = 1234, \n\
        type = PinCode), ...)
activate CSMS

CSMS --> ChargingStation: AuthorizeResponse(idTokenInfo.status  Accepted, ...)
deactivate CSMS

opt
  ChargingStation --> EVDriver: notification
end

@enduml
