@startuml figure_40
!include style.puml

actor "EV Driver" as EVDriver
participant "Charging Station" as ChargingStation
participant "CSMS" as CSMS

EVDriver -> ChargingStation : charging cable plugged in
activate ChargingStation

ChargingStation -> CSMS: \
  TransactionEventRequest(eventType = Started, chargingState = EVConnected,\
  \ntriggerReason = CablePluggedIn)
activate CSMS

CSMS --> ChargingStation: TransactionEventResponse()
deactivate CSMS
deactivate ChargingStation

@enduml
