@startuml figure_47
!include style.puml

actor "EV Driver" as EVDriver
participant "Charging Station" as ChargingStation
participant "CSMS" as CSMS

activate ChargingStation
note over ChargingStation, CSMS
  Charging Station is Offline
end note

note over EVDriver, CSMS
  Offline user authorization successful
end note

opt
  ChargingStation -> EVDriver: notification
end

ChargingStation -> ChargingStation: lock connector

ChargingStation -> ChargingStation: start energy offer

ChargingStation -> ChargingStation: store TransactionEventRequest(offline = true)

note over ChargingStation, CSMS
  Connection loss can be minutes, but can also be days.
end note

note over ChargingStation, CSMS
  Connection restored.
end note

ChargingStation -> CSMS: HeartbeatRequest()
activate CSMS

CSMS --> ChargingStation: HeartbeatResponse()
deactivate CSMS

ChargingStation -> ChargingStation: send queued message()

loop for all queued transaction messages
  ChargingStation -> CSMS: TransactionEventRequest(offline = true)
  activate CSMS

  CSMS --> ChargingStation: TransactionEventResponse(...)
  deactivate CSMS
end

@enduml
