@startuml figure_7
!include style.puml

participant "Charging Station" as ChargingStation
participant "CSMS" as CSMS
participant "Certificate Authority Server" as CAS

activate ChargingStation
note over ChargingStation
  CS certificate is almost due
end note

ChargingStation -> ChargingStation: generate new public / private key pair

ChargingStation -> CSMS: SignCertificateRequest(csr)
activate CSMS

CSMS --> ChargingStation: SignCertificateResponse(Accepted)
deactivate ChargingStation

CSMS -> CAS: forward CSR
activate CAS

CAS -> CAS: sign certificate

CAS --> CSMS: return Signed Certificate
deactivate CAS

CSMS -> ChargingStation: CertificateSignedRequest(certificate)
activate ChargingStation

ChargingStation -> ChargingStation: Verify validity of signed certificate

ChargingStation --> CSMS: CertificateSignedResponse (Accepted/Rejected)
deactivate CSMS

opt key valid
  ChargingStation -> ChargingStation: Switch to new certificate
end

@enduml
