@startuml figure_19
!include style.puml

participant "Operator" as Operator
participant "CSMS1" as CSMS1
participant "CSMS2" as CSMS2
participant "Charging Station" as ChargingStation

Operator -> CSMS1: Change Network Config
activate Operator
activate CSMS1

CSMS1 -[hidden]-> Operator: hidden
deactivate Operator

CSMS1 -> ChargingStation: SetVariablesRequest(NetworkConfigurationPriority)
activate ChargingStation

ChargingStation --> CSMS1: SetVariablesResponse(status: RebootRequired)
deactivate ChargingStation

CSMS1 -> ChargingStation: ResetRequest(OnIdle)
activate ChargingStation

ChargingStation --> CSMS1: ResetResponse(Accepted)
deactivate CSMS1

ChargingStation -> ChargingStation: Reboot

ChargingStation -> CSMS2: BootNotificationRequest(...)
activate CSMS2

CSMS2 --> ChargingStation: BootNotificationResponse(...)
deactivate CSMS2
deactivate ChargingStation

@enduml
