@startuml figure_90
!include style.puml

participant "Charging Station" as ChargingStation
participant "CSMS" as CSMS

note over ChargingStation
  A transaction is ongoing.
end note

ChargingStation -> CSMS: TransactionEventRequest(eventType = Updated,...)
activate ChargingStation
activate CSMS

CSMS -> CSMS: \
  Check for updated\n\
  tariff information

CSMS --> ChargingStation: TransactionEventResponse(PersonalMessage,...)
deactivate CSMS
deactivate ChargingStation

@enduml
