@startuml figure_49
!include style.puml

participant "Charging Station" as ChargingStation
participant "CSMS" as CSMS

note over ChargingStation, CSMS
  A transaction is ongoing.
end note

ChargingStation -> ChargingStation: \
  parking bay detector\
  \nno longer detects the EV
activate ChargingStation

ChargingStation -> CSMS: \
  TransactionEventRequest(eventType = Ended,\
  \ntriggerReason = EVDeparted, stoppedReason = Local, ...)
activate CSMS

CSMS --> ChargingStation: TransactionEventResponse()
deactivate CSMS
deactivate ChargingStation

@enduml
