@startuml figure_3
!include style.puml

participant "Charging Station" as ChargingStation
participant "CSMS" as CSMS

ChargingStation -> CSMS: Client Hello
activate ChargingStation
activate CSMS

CSMS --> ChargingStation: \
  Server Hello \n\
  Server Certificate \n\
  Server Hello Done

deactivate CSMS

ChargingStation -> CSMS: \
  ClientKeyExchange \n\
  [ChangeCipherSpec] \n\
  Finished 
activate CSMS

CSMS --> ChargingStation: \
  [ChangeCipherSpec] \n\
  Finished
deactivate CSMS

ChargingStation -> CSMS: HTTP GET / ProtectedData (Encrypted Communication)
activate CSMS

CSMS --> ChargingStation: HTTP/401 Authentication Required
deactivate CSMS

ChargingStation -> CSMS: \
  HTTP GET / ProtectedData \n\
  Authorization Basic \n\
  Username/Password
activate CSMS

CSMS --> ChargingStation: HTTP 200 / ProtectedData
deactivate CSMS

ChargingStation -> CSMS: Application Data
deactivate ChargingStation
@enduml
