@startuml figure_78
!include style.puml

actor "EV Driver" as EVDriver
participant "CSMS" as CSMS
participant "Charging Station" as ChargingStation

activate EVDriver
EVDriver -> CSMS: reserve
activate CSMS

CSMS -> ChargingStation: ReserveNowRequest(reservation.id, no evseId)
activate ChargingStation

ChargingStation --> CSMS: ReserveNowResponse(status = Accepted)
deactivate ChargingStation

opt
  CSMS --> EVDriver: notification
  deactivate CSMS
  deactivate EVDriver
end

@enduml
