@startuml figure_122
!include style.puml

participant "EV" as EV
participant "Charging Station" as ChargingStation
participant "CSMS" as CSMS

note over ChargingStation
  Starting using Plug-and-Charge.
  TxStartPoint = Authorized, TxStopPoint = EVConnected
end note

note right of EV
  User connects cable
end note

group 15118 Identification, Authentication
  EV -> ChargingStation: ServiceDiscoveryReq()
  activate EV
  activate ChargingStation

  ChargingStation --> EV: ServiceDiscoveryRes()
  deactivate ChargingStation

  EV -> ChargingStation: PaymentServiceSelectionReq()
  activate ChargingStation

  ChargingStation --> EV: PaymentServiceSelectionRes()
  deactivate EV
  deactivate ChargingStation

  opt 15118 Certificate Installation or Update
    EV -> ChargingStation: CertificateUpdateReq()
    activate EV
    activate ChargingStation

    ChargingStation -> CSMS: \
      Get15118EVCertificateRequest(15118SchemaVersion, install/update,\n\
      exiRequest)
    activate CSMS

    CSMS --> ChargingStation: Get15118EVCertificateResponse(status, exiResponse)
    deactivate CSMS

    ChargingStation --> EV: CertificateUpdateRes()
    deactivate EV
    deactivate ChargingStation
  end

  EV -> ChargingStation: PaymentDetailsReq()
  activate EV
  activate ChargingStation

  ChargingStation -> CSMS: AuthorizeRequest(idToken, iso15118CertificateHashData)
  activate CSMS

  CSMS --> ChargingStation: AuthorizeResponse(idTokenInfo, certificateStatus)
  deactivate CSMS

  ChargingStation --> EV: PaymentDetailsRes()
  deactivate ChargingStation

  EV -> ChargingStation: AuthorizationReq()
  activate ChargingStation

  ChargingStation --> EV: AuthorizationRes(EVSEProcessing, ResponseCode)
  deactivate EV

  ChargingStation -> CSMS: \
    TransactionEventRequest(eventType = Started,\n\
    triggerReason = Authorized, chargingState = EVConnected, ...)
  activate CSMS

  CSMS --> ChargingStation: TransactionEventResponse(...)
  deactivate ChargingStation
  deactivate CSMS
end

group seq 15118 Target Setting and charge Scheduling
  EV -> ChargingStation: ChargeParameterDiscoveryReq()
  activate EV
  activate ChargingStation

  ChargingStation -> CSMS: NotifyEVChargingNeedsRequest(chargingNeeds, evseId, ...)
  activate CSMS

  CSMS --> ChargingStation: NotifyEVChargingNeedsResponse(Accepted)
  deactivate CSMS

  CSMS -> ChargingStation: SetChargingProfileRequest(evseId, chargingProfile)
  activate CSMS

  ChargingStation --> CSMS: SetChargingProfileResponse(Accepted)
  deactivate CSMS

  ChargingStation --> EV: ChargeParameterDiscoveryRes(SAScheduleList)
  deactivate EV
  deactivate ChargingStation

  EV -> ChargingStation: PowerDeliveryReq(ChargeProcess=Start)
  activate EV
  activate ChargingStation

  ChargingStation -> ChargingStation: Contactor Close

  ChargingStation -> EV: PowerDeliveryRes()
  deactivate EV
  deactivate ChargingStation

  ChargingStation -> CSMS: \
    TransactionEventRequest(eventType = Updated,\n\
    triggerReason = ChargingStateChanged, chargingState = Charging, ...)
  activate ChargingStation
  activate CSMS

  CSMS --> ChargingStation: TransactionEventResponse(...)
  deactivate CSMS

  ChargingStation -> CSMS: \
    NotifyEVChargingScheduleRequest(timeBase, evseId,\n\
      chargingSchedule)
  activate CSMS

  CSMS --> ChargingStation: NotifyEVChargingScheduleResponse(status)
  deactivate ChargingStation
  deactivate CSMS
end

note right of EV
  EV is charging...
end note

note right of EV
  User terminates charging
end note

group Stopping Transaction
  EV -> ChargingStation: PowerDeliveryReq(ChargeProcess=Stop)
  activate EV
  activate ChargingStation

  ChargingStation -> ChargingStation: Contactor Open

  ChargingStation --> EV: PowerDeliveryRes()
  deactivate EV
  deactivate ChargingStation

  EV -> ChargingStation: SessionStopReq()
  activate EV
  activate ChargingStation

  ChargingStation --> EV: SessionStopRes()
  deactivate EV
  deactivate ChargingStation

  ChargingStation -> CSMS: \
    TransactionEventRequest(eventType = Updated, \n\
      triggerReason = ChargingStateChanged, chargingState = EVConnected, ...)
  activate ChargingStation
  activate CSMS

  CSMS --> ChargingStation: TransactionEventResponse(...)
  deactivate ChargingStation
  deactivate CSMS
end

note right of EV
  User disconnects cable
end note

ChargingStation -> CSMS: \
  TransactionEventRequest(eventType = Ended, \n\
    triggerReason = EVCommunicationLost, chargingState = Idle, ...)
activate ChargingStation
activate CSMS

CSMS --> ChargingStation: TransactionEventResponse(...)
deactivate ChargingStation
deactivate CSMS

@enduml
