@startuml figure_43
!include style.puml

actor "EV Driver" as EVDriver
participant "Charging Station" as ChargingStation
participant "CSMS" as CSMS

activate ChargingStation

note over EVDriver, ChargingStation
  EV 연결됨
end note

note over ChargingStation, CSMS
  사용자 인증 성공
end note

ChargingStation -> CSMS: \
  TransactionEventRequest(eventType = Started, chargingState = Charging,\
  \ntriggerReason = ChargingStateChanged)
activate CSMS

CSMS --> ChargingStation: TransactionEventResponse()
deactivate ChargingStation
deactivate CSMS

@enduml
