@startuml figure_136
!include style.puml

actor "CSO" as CSO
participant "CSMS" as CSMS
participant "Charging Station" as ChargingStation

CSO -> CSMS : 변수 모니터링을 지우거나 제거하기 위한 요청

CSMS -> ChargingStation: ClearVariableMonitoringRequest(id)
activate CSMS
activate ChargingStation

ChargingStation --> CSMS: ClearVariableMonitoringResponse(status)
deactivate CSMS
deactivate ChargingStation

@enduml
