@startuml figure_41
!include style.puml

actor "EV Driver" as EVDriver
participant "Charging Station" as ChargingStation
participant "CSMS" as CSMS

EVDriver -> ChargingStation: ID 제시
activate ChargingStation

note over ChargingStation, CSMS
  사용자 인증 성공
end note

ChargingStation -> CSMS: \
  TransactionEventRequest(eventType = Started,\
  \ntriggerReason = Authorized)
activate CSMS

CSMS --> ChargingStation: TransactionEventResponse()
deactivate CSMS
deactivate ChargingStation

@enduml
