@startuml figure_108
!include style.puml

participant "CSMS" as CSMS
participant "Charging Station" as ChargingStation

CSMS -> ChargingStation: GetChargingProfileRequest(requestId = 123, chargingProfile,...)
activate CSMS
activate ChargingStation

ChargingStation --> CSMS: GetChargingProfileResponse(status = Accepted)
deactivate CSMS

loop tbc = true인 동안
  ChargingStation -> CSMS: ReportChargingProfilesRequest(requestId = 123, ...)
  activate CSMS

  CSMS --> ChargingStation: ReportChargingProfilesResponse()
  deactivate CSMS
end

@enduml
