@startuml figure_67
!include style.puml

participant "External Trigger" as ExternalTrigger
participant "CSMS" as CSMS
participant "Charging Station" as ChargingStation

note left of ChargingStation
  TxStartPoint = EVConnected
end note

ExternalTrigger -> CSMS: 원격 시작
activate ExternalTrigger
activate CSMS

CSMS -> ChargingStation: RequestStartTransactionRequest(idToken = ABCD, remoteStartId = 123)
activate ChargingStation

ChargingStation --> CSMS: RequestStartTransactionResponse(status = Accepted)

opt 
  CSMS -> ExternalTrigger: 알림
  deactivate CSMS
end
deactivate ExternalTrigger

opt AuthorizeRemoteStart = true
  ChargingStation -> CSMS: AuthorizeRequest(idToken = ABCD)
  activate CSMS

  CSMS --> ChargingStation: AuthorizeResponse(idTokenInfo)
  deactivate CSMS
end

ExternalTrigger -> ChargingStation: 케이블 연결

ChargingStation -> CSMS: StatusNotificationRequest(Occupied)
activate CSMS

CSMS --> ChargingStation: StatusNotificationResponse()
deactivate CSMS

note left of ChargingStation
  CablePluggedIn 대신 triggerReason = RemoteStart 이용! (F02.FR.21)
end note

ChargingStation -> CSMS: \
  TransactionEventRequest(eventType = Started, transactionId = AB1234, idToken = ABCD, \
  \nchargingState = EVConnected, evse.id = 1, evse.connectorId = 1, meterValues, \
  \ntriggerReason = RemoteStart, remoteStartId = 123, ...)
activate CSMS

CSMS --> ChargingStation: TransactionEventResponse(...)
deactivate CSMS
activate ChargingStation

opt 케이블이 영구적으로\n연결되지 않음
  ChargingStation -> ChargingStation: 커넥터 잠금
end

ChargingStation -> ChargingStation: 에너지 제공 시작

ChargingStation -> CSMS: \
  TransactionEventRequest(eventType = Updated, chargingState = Charging,\
  \ntriggerReason = ChargingStateChanged, ...)
activate CSMS

CSMS --> ChargingStation: TransactionEventResponse(...)
deactivate CSMS
deactivate ChargingStation

@enduml
