@startuml figure_135
!include style.puml

actor "CSO" as CSO
participant "CSMS" as CSMS
participant "Charging Station" as ChargingStation

CSO -> CSMS : 모니터링 심각도 수준 설정 요청

CSMS -> ChargingStation: SetMonitoringLevelRequest(severity)
activate CSMS
activate ChargingStation

ChargingStation --> CSMS: SetMonitoringLevelResponse(status)
deactivate CSMS
deactivate ChargingStation

@enduml
