@startuml figure_14
!include style.puml

actor "CSO" as CSO
participant "CSMS" as CSMS
participant "Charging Station" as ChargingStation

CSO -> CSMS: 한 개 이상의 변수 설정을 위한 요청

CSMS -> ChargingStation: SetVariablesRequest(setVariableData)
activate CSMS
activate ChargingStation

ChargingStation --> CSMS: SetVariablesResponse(setVariableResult)
deactivate CSMS
deactivate ChargingStation

@enduml
