@startuml figure_33
!include style.puml

actor "EV Driver" as EVDriver
participant "Charging Station" as ChargingStation

ChargingStation -> ChargingStation: connection loss
activate EVDriver

EVDriver -> ChargingStation: IdToken 제시
activate ChargingStation

ChargingStation -> ChargingStation: \
  local authorization list() 확인 \
  \n[cached tariff: 0.23/kWh]

opt
  ChargingStation --> EVDriver: \
    알림\
    \n[tariff: 0.23/kWh]
  deactivate EVDriver
end

ChargingStation -> ChargingStation: 커넥터 잠금

ChargingStation -> ChargingStation: 에너지 제공 시작

@enduml
