@startuml figure_140
!include style.puml

participant "CSMS" as CSMS
participant "Charging Station" as ChargingStation

CSMS -> ChargingStation: CustomerInformationRequest(report, clear = true)
activate CSMS
activate ChargingStation

ChargingStation --> CSMS: CustomerInformationResponse()
deactivate CSMS

opt report = true인 경우
  loop 각 리포트 파트에 대해
    ChargingStation -> CSMS: NotifyCustomerInformationRequest()
    activate CSMS
    activate ChargingStation

    CSMS --> ChargingStation: NotifyCustomerInformationResponse()
    deactivate CSMS
    deactivate ChargingStation
  end
end

ChargingStation -> ChargingStation: 고객 정보 제거
deactivate ChargingStation

@enduml
