@startuml figure_61
!include style.puml

participant "Charging Station" as ChargingStation
participant "CSMS" as CSMS

activate ChargingStation
note over ChargingStation, CSMS
  충전기가 오프라인이고 트랜잭션이 발생함
end note

note over ChargingStation, CSMS
  연결 재개됨
end note

ChargingStation -> CSMS: HeartbeatRequest()
activate CSMS

CSMS --> ChargingStation: HeartbeatResponse()
deactivate CSMS

ChargingStation -> ChargingStation: 큐에 저장된 메시지 전송

loop 연결 끊김 이후 큐에 저장된 모든 TransactionEvent에 대해
  ChargingStation -> CSMS: TransactionEventRequest(transactionId = X, offline = true)
  activate CSMS

  CSMS --> ChargingStation: TransactionEventResponse()
  deactivate CSMS
  deactivate ChargingStation
end

@enduml
