@startuml figure_56
!include style.puml

actor "EV Driver" as EVDriver
participant "Charging Station" as ChargingStation
participant "CSMS" as CSMS

note over EVDriver, CSMS
  사용자 인증 성공
end note

ChargingStation -> CSMS: \
  TransactionEventRequest(eventType = Updated, transactionId = AB1234, seqNo = N + 1, timestamp,\
  \ntriggerReason = StopAuthorized, idToken.id = 1234)
activate ChargingStation
activate CSMS

CSMS --> ChargingStation: TransactionEventResponse(idTokenInfo.status)
deactivate ChargingStation
deactivate CSMS

opt 케이블이 영구적으로 연결되지 않음 & (동일 ID 또는 인증)
  ChargingStation -> ChargingStation: 커넥터 잠금 해제
end

alt TxStopPoint = Authorized 또는 PowerPathClosed 또는 EnergyTransfer
  ChargingStation -> CSMS: \
    TransactionEventRequest(eventType = Ended, transactionId = AB1234, seqNo = N + 2, timestamp,\
    \ntriggerReason = ChargingStateChanged, chargingState = EVConnected, stoppedReason = Local, meterValues)
  activate ChargingStation
  activate CSMS

  CSMS --> ChargingStation: TransactionEventResponse()
  deactivate ChargingStation
  deactivate CSMS
else TxStopPoint = EVConnected 또는 TxStopPoint = ParkingBayOccupancy
  ChargingStation -> CSMS: \
    TransactionEventRequest(eventType = Updated, transactionId = AB1234, seqNo = N + 2, timestamp,\
    \ntriggerReason = ChargingStateChanged, chargingState = EVConnected, meterValues)
  activate ChargingStation
  activate CSMS

  CSMS --> ChargingStation: TransactionEventResponse()
  deactivate CSMS
  deactivate ChargingStation
end

EVDriver -> ChargingStation: 케이블 연결 해제

ChargingStation -> CSMS: StatusNotificationRequest(Available)
activate ChargingStation
activate CSMS

CSMS --> ChargingStation: StatusNotificationResponse()
deactivate ChargingStation
deactivate CSMS

alt TxStopPoint = EVConnected
  ChargingStation -> CSMS: \
    TransactionEventRequest(eventType = Ended, transactionId = AB1234, seqNo = N + 3, timestamp,\
    \ntriggerReason = EVCommunicationLost, stoppedReason = Local)
  activate ChargingStation
  activate CSMS

  CSMS --> ChargingStation: TransactionEventResponse()
  deactivate ChargingStation
  deactivate CSMS
else TxStopPoint = ParkingBayOccupancy
  ChargingStation -> CSMS: \
    TransactionEventRequest(eventType = Updated, transactionId = AB1234, seqNo = N + 3, timestamp,\
    \ntriggerReason = EVCommunicationLost)
  activate CSMS
  activate ChargingStation

  CSMS --> ChargingStation: TransactionEventResponse()
  deactivate ChargingStation
  deactivate CSMS
end

EVDriver -> ChargingStation: 주차 자리 밖으로 운전

alt TxStopPoint = ParkingBayOccupancyoend
  ChargingStation -> CSMS: \
    TransactionEventRequest(eventType = Ended, transactionId = AB1234, seqNo = N + 3, timestamp,\
    \ntriggerReason = EVDeparted, stoppedReason = Local)
  activate CSMS
  activate ChargingStation

  CSMS --> ChargingStation: TransactionEventResponse()
  deactivate CSMS
  deactivate ChargingStation
end

@enduml
