@startuml figure_83
!include style.puml

actor "EV Driver" as EVDriver
participant "CSMS" as CSMS
participant "Charging Station" as ChargingStation

EVDriver -> CSMS: 예약
activate CSMS

CSMS -> ChargingStation: ReserveNowRequest(connectorId, idToken = TOKEN_A, groupIdToken = TOKEN_P)
activate ChargingStation

ChargingStation --> CSMS: ReserveNowResponse(status = Accepted)
deactivate CSMS

opt 특정 EVSE가 이 예약에 이용된 경우
  ChargingStation -> CSMS: StatusNotificationRequest(status = Reserved, ...)
  activate CSMS

  CSMS --> ChargingStation: StatusNotificationResponse()
  deactivate CSMS
  deactivate ChargingStation
end

EVDriver -> ChargingStation: IdToken(TOKEN_B) 제시
activate ChargingStation

alt TOKEN_B가 Local Authorization List 또는 Authorization Cache에 없는 경우
  ChargingStation -> CSMS: AuthorizeRequest(idToken = TOKEN_B)
  activate CSMS

  CSMS --> ChargingStation: AuthorizeResponse(idTokenInfo(groupIdToken = TOKEN_P))
  deactivate CSMS
end

ChargingStation ->o] : 일반 트랜잭션 진행
deactivate ChargingStation

@enduml
