@startuml figure_6
!include style.puml

participant "CSMS" as CSMS
participant "Charging Station" as ChargingStation
participant "Certificate Authority Server" as CAS

note over CSMS, ChargingStation
  CS 인증서 만료 기간 도래
end note

CSMS -> ChargingStation: TriggerMessageRequest(SignCertificate)
activate CSMS
activate ChargingStation

ChargingStation --> CSMS: TriggerMessageResponse(Accepted)
deactivate CSMS

ChargingStation -> ChargingStation: 신규 공개 / 개인 키 쌍 발급

ChargingStation -> CSMS: SignCertificateRequest(csr)
activate CSMS
CSMS --> ChargingStation: SignCertificateResponse(Accepted)
deactivate ChargingStation

CSMS -> CAS: CSR 포워딩
activate CAS
CAS -> CAS: 인증서 서명

CAS --> CSMS: 서명된 인증서 반환
deactivate CAS

CSMS -> ChargingStation: CertificateSignedRequest(certificate)
activate ChargingStation

ChargingStation -> ChargingStation: 서명된 인증서 유효성 검증

ChargingStation --> CSMS: CertificateSignedResponse (Accepted/Rejected)
deactivate CSMS

opt 키 유요함
  ChargingStation -> ChargingStation: 새 인증서로 변경
end

@enduml
