@startuml figure_80
!include style.puml

actor "EV Driver" as EVDriver
participant "CSMS" as CSMS
participant "Charging Station" as ChargingStation

activate EVDriver
EVDriver -> CSMS: 예약
activate CSMS

CSMS -> ChargingStation: ReserveNowRequest(ConnectorType is specified AND no evseId)
activate ChargingStation

ChargingStation --> CSMS: ReserveNowResponse(status = Accepted)

opt
  CSMS --> EVDriver: 알림
  deactivate CSMS
  deactivate EVDriver
end

@enduml
