@startuml figure_77
!include style.puml

actor "User" as User
participant "Charging Station" as ChargingStation
participant "CSMS" as CSMS

note over ChargingStation
  케이블 연결됨
end note

note over User, CSMS
  사용자 인증 성공
end note

ChargingStation ->o ChargingStation: 커넥터 잠금 시도 실패

ChargingStation -> CSMS: \
  NotifyEventRequest(component = ConnectorPlugRetentionLock, \n\
                variable = Problem, value = true)
activate CSMS
activate ChargingStation

CSMS --> ChargingStation: NotifyEventResponse()
deactivate ChargingStation
deactivate CSMS

ChargingStation --> User: 선택적(optional) 알림

@enduml
