@startuml figure_15
!include style.puml

actor "CSO" as CSO
participant "CSMS" as CSMS
participant "Charging Station" as ChargingStation

CSO -> CSMS: 다수의 변수 요청

CSMS -> ChargingStation: getVariablesRequest(getVariableData)
activate CSMS
activate ChargingStation

ChargingStation --> CSMS: getVariablesResponse(getVariableResult)
deactivate ChargingStation

opt
  CSMS -> CSO: 알림
  deactivate CSMS
end

@enduml
