@startuml figure_6
!include component_diagram_style.puml

left to right direction

node "Central System" as CentralSystem

folder "Charge Point: CP10" as CP10Folder {
  node "Charge Point\nCP10" as CP10

  node "Connector\n1" as CP10_C1
  node "Connector\n2" as CP10_C2
}

folder "Charge Point: CP11" as CP11Folder {
  node "Charge Point\nCP11" as CP11

  node "Connector\n1" as CP11_C1
  node "Connector\n2" as CP11_C2
}

actor "EV1" as EV1
actor "EV2" as EV2

note top of CentralSystem
  Central System은 물리적인
  그리드 연결(grid connection) 제한을
  설정합니다.
end note

CentralSystem -down-> CP10 : OCPP 차징 프로파일
CentralSystem -down-> CP11 : OCPP 차징 프로파일

CP10 -down- CP10_C1
CP10 -down- CP10_C2

CP11 -down- CP11_C1
CP11 -down- CP11_C2

CP10_C1 -down[dotted]-> EV1 : CP 신호 \
\n(Control Pilot Signal)
CP10_C2 -down[dotted]-> EV2 : CP 신호 \
\n(Control Pilot Signal)

@enduml