@startuml figure_8
!include style.puml

actor "User" as User
participant "EV" as EV
participant "Charge Point" as ChargePoint
participant "Central System" as CentralSystem

note over User, CentralSystem
  RFID 또는 다른 인증 방식의 인증
end note

ChargePoint -> EV : 최대 전류량 제한 설정
activate ChargePoint

ChargePoint -> ChargePoint : 전원 켜짐

EV -> ChargePoint : 충전 시작
activate EV
deactivate ChargePoint

ChargePoint -[hidden]-> ChargePoint

ChargePoint -> CentralSystem : \
StartTransaction.req(connectorId, idTag, meterStart, timestamp, [reservationId])
activate ChargePoint

activate CentralSystem
CentralSystem --> ChargePoint : \
StartTransaction.conf(idTagInfo, transactionId)
deactivate CentralSystem

group 차징 프로파일 기반으로 loop이 변경됨
else 차징 프로파일에 있는 매 주기 기준

  ChargePoint -> ChargePoint : 차징 프로파일 기반으로 전력량 제한 설정
  note right
    충전기는 최대 전류량 변경이 필요할 때마다
    CP(Control Pilot) 신호를 이용하여
    차징 프로파일을 구현합니다.
  end note

  ChargePoint -> EV : 최대 전류량 제한 설정
  deactivate ChargePoint

  opt Change of limits by Central System
    CentralSystem -> ChargePoint :\
      SetChargingProfile.req(ConnectorId, ChargingProfileId, [transactionId],\
      \n**ChargingProfilePurpose: TxProfile** , ChargingProfileType, recurrencyKind, ValidFrom,\
      \nValidTo, ChargingSchedule)
    activate CentralSystem
    activate ChargePoint

    note right of CentralSystem
      Central System은 차징 프로파일을
      변경해야 하는지 결정합니다.
    end note

    ChargePoint --> CentralSystem : SetChargingProfile.conf(Accepted)
    deactivate ChargePoint
    deactivate CentralSystem
  end
end

note over User, CentralSystem
  RFID 또는 다른 인증 방식의 인증
end note

ChargePoint --> EV : 충전 종료

ChargePoint -> ChargePoint : 전원 꺼짐

ChargePoint -> CentralSystem : \
  StopTransaction.req(meterStop, timestamp,\
  \ntransactionId, reason, [idTag], [transactionData])
activate ChargePoint
activate CentralSystem

CentralSystem --> ChargePoint : StopTransaction.conf([idTagInfo])
deactivate CentralSystem
deactivate ChargePoint
deactivate EV

@enduml