@startuml figure_5
!include style.puml

participant "Session" as Session
participant "Transaction" as Transaction
participant "Energy Offer" as EnergyOffer
participant "Energy Flow" as EnergyFlow

activate Session

group Charging Session

  note over Session
    충전 세션은 사용자 또는 EV와 처음 상호작용을 하는 시점에 시작됩니다.
    이 상호작용은 카드로 결제를 하거나,
    원격 시작(remote start of transaction)을 진행,
    커넥터와 차량을 연결,
    주차장의 주차감지기를 통해 차량이 주차장에 있는지 확인하는 등의 작업을 수행합니다.
  end note

  group Transaction
    Transaction -[hidden]-> Transaction
    activate Transaction
    note over Transaction
      Transaction은 충전 조건을 모두 만족하는 시점에 시작됩니다.
      예를 들어, EV가 충전기에 연결되어 있고, 사용자가 인증을 받은 경우가 이에 해당됩니다.
    end note

    EnergyOffer -[hidden]-> EnergyOffer
    activate EnergyOffer
    group EnergyOfferPeriod
      note over EnergyOffer
        Energy Offer Period는 충전기(EVSE)가 준비되고,
        충전기(EVSE)가 충전을 시작할 수 있을 때 시작됩니다.
      end note

    group EnergyTransferPeriod
      EnergyFlow -[hidden]-> EnergyFlow
      activate EnergyFlow
      note right of EnergyFlow
        에너지가 전달됩니다.
      end note
      EnergyFlow -[hidden]-> EnergyOffer
      deactivate EnergyFlow
    end
    note right of EnergyOffer
      EnergyOfferPeriod 기간 동안 배터리의 발열/완충,
      EV 내부 Smart Charging과 같은 원인으로 인해
      EV가 충전되지 않을 수 있습니다.
    end note
    group EnergyTransferPeriod
      EnergyFlow -[hidden]-> EnergyFlow
      activate EnergyFlow
      note right of EnergyFlow
        에너지가 전달됩니다.
      end note
      EnergyFlow -[hidden]-> EnergyOffer
      deactivate EnergyFlow
    end
    deactivate EnergyOffer
  end

    group EnergyOfferSuspendPeriod
      Transaction -[hidden]-> EnergyOffer
      note over EnergyOffer
        Transaction 동안, Smart Charging 또는
        local balancing과 같은 원인으로 인해
        충전기(EVSE)가 EV로 EnergyOffer를 중단하는
        기간이 존재할 수 있습니다.
      end note
    end

    group EnergyOfferPeriod
      Transaction -[hidden]-> Transaction
      activate EnergyOffer
      group EnergyTransferPeriod
        EnergyFlow -[hidden]-> EnergyFlow
        activate EnergyFlow
        note right of EnergyFlow
          에너지가 전달됩니다.
        end note
        EnergyFlow -[hidden]-> EnergyOffer
        deactivate EnergyFlow
      end
      deactivate EnergyOffer
    end
    deactivate Transaction

    note over Transaction
      Transaction은 사용자가 transaction 중단을 요청하고,
      이 요청이 승인되는 경우와 같이
      충전을 위한 조건(precondition)이 모두 false인
      시점에 종료됩니다.
    end note
  end
  deactivate Session

  note over Session
    Session은 충전기가 차량에 연결되지 않고,
    주차 공간이 비어 있을 때와 같이
    충전소가 다시 사용 가능한(available) 상태일 때 종료됩니다.
  end note
end

@enduml