@startuml figure_11
!include style.puml

actor "User" as User
participant "EV" as EV
participant "Charge Point" as ChargePoint
participant "Local Controller" as LocalController
participant "Central System" as CentralSystem

note over User, CentralSystem
  RFID 또는 다른 인증 방식의 인증
end note

ChargePoint -> EV : 최대 전류량 제한 설정
activate ChargePoint

ChargePoint -> ChargePoint : 전원 켜짐

EV -> ChargePoint : 충전 시작
activate EV

ChargePoint -> LocalController : \
  StartTransaction.req(connectorId, idTag, meterStart, timestamp,\
  \n[reservationId])

activate LocalController
LocalController --> CentralSystem : \
  StartTransaction.req(connectorId, idTag, meterStart, timestamp,\
  \n[reservationId])
activate CentralSystem

CentralSystem -> LocalController : StartTransaction.conf(idTagInfo, transactionId)
deactivate CentralSystem

LocalController --> ChargePoint : StartTransaction.conf(idTagInfo, transactionId)
deactivate LocalController

group loop Change according to charging profile 
else for each interval period in charging profile

  ChargePoint -> ChargePoint : 차징 프로파일 기반으로 전력량 제한 설정
  note right
    충전기는 최대 전류량 변경이 필요할 때마다
    CP(Control Pilot) 신호를 이용하여
    차징 프로파일을 구현합니다.
  end note

  ChargePoint -> EV : 최대 전류량 제한 설정
  deactivate ChargePoint

  opt Change of limits by controller
    LocalController -> ChargePoint :\
      SetChargingProfile.req(connectorId, csChargingProfiles)
    activate LocalController
    activate ChargePoint

    note right of LocalController
      로컬 컨트롤러가 차징 프로파일을
      변경해야 할 지 결정합니다.
    end note

    ChargePoint --> LocalController : SetChargingProfile.conf(Accepted)
    deactivate ChargePoint
    deactivate LocalController
  end
end

note over User, CentralSystem
  RFID 또는 다른 인증 방식의 인증
end note

ChargePoint -> EV : 충전 종료

ChargePoint -> ChargePoint : 전원 꺼짐

ChargePoint -> LocalController : \
  StopTransaction.req(meterStop, timestamp,\
  \ntransactionId, reason, [idTag], [transactionData])
activate ChargePoint
activate LocalController

LocalController -> CentralSystem : \
  StopTransaction.req(meterStop, timestamp,\
  \ntransactionId, reason, [idTag], [transactionData])
activate CentralSystem

CentralSystem --> LocalController : StopTransaction.conf([idTagInfo])
deactivate CentralSystem

LocalController --> ChargePoint : StopTransaction.conf([idTagInfo])
deactivate LocalController
deactivate ChargePoint
deactivate EV

@enduml