@startuml figure_10
!include style.puml

participant "Charge Point" as ChargePoint
participant "Local Controller" as LocalController
participant "CSO Central System" as CentralSystem

group opt Set local group limits
  CentralSystem -> LocalController : \
    SetChargingProfile.req( **connectorId: 0** , \
    \n**chargingprofilePurpose: ChargepointMaxProfile** , \
    \n**chargingProfileKind: absolute** , validFrom, validTo)

  activate LocalController
  note right of CentralSystem
    로컬 커넥터 그룹에 대한 제한은
    로컬 컨트롤러에서 사전 설정하거나,
    CSO에 의해 동적으로 설정할 수 있습니다.
  end note

  LocalController -> CentralSystem : SetChargingProfile.conf(Accepted)
  deactivate LocalController
end

LocalController -> ChargePoint : \
  SetChargingProfile.req( **connectorId: 0** ,\
  \n**chargingprofilePurpose: ChargepointMaxProfile** ,\
  \n**chargingProfileKind: absolute** , validFrom, validTo)

activate ChargePoint
note right of LocalController
  로컬 컨트롤러는 충전기에
  전력량 제한을 할당합니다.
end note

ChargePoint -> LocalController : SetChargingProfile.conf(Accepted)
deactivate ChargePoint

@enduml