@startuml figure_2
!include style.puml

participant "Charge Point" as ChargePoint
participant "Central System" as CentralSystem

ChargePoint -> CentralSystem: UpdateFirmware.req(location, retrieveDate, [retries], [retryInterval])
activate ChargePoint
activate CentralSystem

CentralSystem --> ChargePoint : UpdateFirmware.conf()
deactivate ChargePoint
deactivate CentralSystem

note over ChargePoint
펌웨어 다운로드중...
end note

ChargePoint -> CentralSystem : FirmwareStatusNotification.req( **status: Downloaded** )
activate ChargePoint
activate CentralSystem

CentralSystem  --> ChargePoint : FirmwareStatusNotification.conf()
deactivate ChargePoint
deactivate CentralSystem

note over ChargePoint
설치중...
end note
ChargePoint -> CentralSystem : FirmwareStatusNotification.req( **status: Installed** )
activate ChargePoint
activate CentralSystem

CentralSystem  --> ChargePoint : FirmwareStatusNotification.conf()
deactivate ChargePoint
deactivate CentralSystem

note over ChargePoint
재부팅
end note
ChargePoint -> CentralSystem :\
BootNotification.req(chargePointModel, chargePointVendor, [chargeBoxSerialNumber],\n\
\t\t\t\t[chargePointSerialNumber],[firmwareVersion], [iccid], [imsi],\n\
\t\t\t\t[meterSerialNumber], [meterType])

activate ChargePoint
activate CentralSystem
CentralSystem  --> ChargePoint : BootNotification.conf(currentTime, heartbeatInterval, status)

deactivate ChargePoint
deactivate CentralSystem
@enduml