@startuml figure_41
!include style.puml

participant "Charge Point" as ChargePoint
participant "Central System" as CentralSystem

CentralSystem -> ChargePoint : UpdateFirmware.req(location, retrieveDate, [retries], [retryInterval])
activate ChargePoint
activate CentralSystem

ChargePoint --> CentralSystem : UpdateFirmware.conf()
deactivate CentralSystem

note over ChargePoint
  retrieveDate를 기다리는 중...
end note

ChargePoint -> CentralSystem : FirmwareStatusNotification.req( **status: Downloading** )
activate CentralSystem

CentralSystem --> ChargePoint : FirmwareStatusNotification.conf()
deactivate CentralSystem

note over ChargePoint
  다운로드 중...
end note

ChargePoint -> CentralSystem : FirmwareStatusNotification.req( **status: Downloaded ** )
activate CentralSystem

CentralSystem --> ChargePoint : FirmwareStatusNotification.conf()
deactivate CentralSystem

note over ChargePoint
  transaction이 완료되기를 기다리는 중...
end note

ChargePoint -> CentralSystem : FirmwareStatusNotification.req( **status: Installing ** )
activate CentralSystem

CentralSystem --> ChargePoint : FirmwareStatusNotification.conf()
deactivate CentralSystem
deactivate ChargePoint

note over ChargePoint
  설치 중...
end note

alt 펌웨어 업데이트 이후 자동 재부팅
  note over ChargePoint
    재부팅
  end note
  
  ChargePoint -> CentralSystem : \
  BootNotification.req(chargePointModel, chargePointVendor, [chargeBoxSerialNumber],\n\
  \t[chargePointSerialNumber], [firmwareVersion], [iccid], [imsi], [meterSerialNumber],\n\
  \t[meterType])
  activate ChargePoint
  activate CentralSystem

  CentralSystem --> ChargePoint : BootNotification.conf(currentTime, heartbeatInterval, status)
  deactivate CentralSystem

  ChargePoint -> CentralSystem : FirmwareStatusNotification.req( status: **Installed** )
  activate CentralSystem

  CentralSystem --> ChargePoint : FirmwareStatusNotification.conf()
  deactivate CentralSystem
  deactivate ChargePoint
else 펌웨어 업데이트 이후 수동 재부팅
  ChargePoint -> CentralSystem : FirmwareStatusNotification.req( status: **Installed** )
  activate ChargePoint
  activate CentralSystem

  CentralSystem --> ChargePoint : FirmwareStatusNotification.conf()
  deactivate ChargePoint

  CentralSystem -> ChargePoint : Reset.req(Hard)
  activate ChargePoint

  ChargePoint --> CentralSystem : Reset.conf()
  deactivate ChargePoint
  deactivate CentralSystem

  note over ChargePoint
    재부팅
  end note

  ChargePoint -> CentralSystem : \
    BootNotification.req(chargePointModel, chargePointVendor, [chargeBoxSerialNumber],\n\
    \t[chargePointSerialNumber], [firmwareVersion], [iccid], [imsi], [meterSerialNumber],\n\
    \t[meterType])
  activate ChargePoint
  activate CentralSystem

  CentralSystem --> ChargePoint : BootNotification.conf(currentTime, heartbeatInterval, status)
  deactivate ChargePoint
  deactivate CentralSystem
end

@enduml