@startuml figure_9
!include component_diagram_style.puml

left to right direction

node "Central System" as CentralSystem

folder "Local group" {
  node "Local Controller\nCP00" as LocalControllerCP00

  node "Charge Point\nCP03" as CP03
  node "Charge Point\nCP02" as CP02
  node "Charge Point\nCP01" as CP01

  actor "EV1" as EV1
  actor "EV2" as EV2

  note top of LocalControllerCP00
    Local Controller는
    전체 충전기 그룹의 전력 사용량을
    사전에 설정된 최대 용량 미만으로
    제한합니다.
  end note
}

CentralSystem -down-> LocalControllerCP00 : OCPP ChargePointMaxProfile

LocalControllerCP00 -down-> CP03 : OCPP 차징 프로파일
LocalControllerCP00 -down-> CP02 : OCPP 차징 프로파일
LocalControllerCP00 -down- CP01 

CP03 -down[dotted]-> EV1 : CP 신호 \
\n(Control Pilot Signal)
CP02 -down[dotted]-> EV2 : CP 신호 \
\n(Control Pilot Signal)

CP03 -left[hidden]- CP02
CP02 -left[hidden]- CP01

@enduml